import type { FieldSource, ModuleSlug } from "@/lib/types";

export const excelSheets: { slug: ModuleSlug; sheet: string; role: string }[] = [
  { slug: "setup", sheet: "ProjectSetup02", role: "تعریف پروژه و تنظیمات پایه" },
  { slug: "methodology", sheet: "MethodologyMap03", role: "روش‌شناسی، فرمول‌ها و trace" },
  { slug: "master-data", sheet: "MasterData04", role: "داده‌های پایه و dropdownها" },
  { slug: "macro", sheet: "MarcoAssumptions05", role: "تورم، FX، مالیات و نرخ تنزیل" },
  { slug: "scenarios", sheet: "ScenarioManager06", role: "سناریو و شوک‌ها" },
  { slug: "industry-template", sheet: "IndustryTemplate07", role: "قالب صنعت" },
  { slug: "market-demand", sheet: "MarketDemand08", role: "بازار، تقاضا و قیمت" },
  { slug: "capacity-production", sheet: "CapacityProduction09", role: "ظرفیت و تولید" },
  { slug: "direct-costs", sheet: "COGS-DirectCost10", role: "COGS و هزینه مستقیم" },
  { slug: "opex", sheet: "Opex-Indirect11", role: "هزینه‌های غیرمستقیم عملیاتی" },
  { slug: "capex", sheet: "Capex12", role: "CAPEX و دارایی ثابت" },
  { slug: "working-capital", sheet: "WorkingCapital13", role: "سرمایه در گردش" },
  { slug: "financing", sheet: "Financing14", role: "وام، DSCR و تأمین مالی" },
  { slug: "construction-cashflow", sheet: "ConstructionCashFlow", role: "جریان نقد ماهانه ساخت" },
  { slug: "financial-statements", sheet: "FinancialStatements16", role: "صورت‌های مالی" },
  { slug: "valuation", sheet: "DCF-Valuation17", role: "DCF، NPV، IRR و payback" },
  { slug: "economic-analysis", sheet: "EconomicAnalysis18", role: "تحلیل اقتصادی" },
  { slug: "sensitivity", sheet: "Sensivity19", role: "تحلیل حساسیت" },
  { slug: "monte-carlo", sheet: "MonteCarlo20", role: "شبیه‌سازی مونت‌کارلو" },
  { slug: "dashboard-executive", sheet: "DashboardExecutive21", role: "داشبورد اجرایی" },
  { slug: "dashboard-bank", sheet: "DashboardBank22", role: "داشبورد بانک" },
  { slug: "dashboard-management", sheet: "DashboardManagement23", role: "داشبورد مدیریت" },
  { slug: "report", sheet: "ReportPack24", role: "گزارش نهایی" },
  { slug: "exports", sheet: "ReportPack24", role: "خروجی PDF/Word/Excel" },
  { slug: "settings", sheet: "ProjectSetup02", role: "تنظیمات workspace" },
  { slug: "overview", sheet: "DashboardExecutive21", role: "خلاصه پروژه" },
];

export const source = (sourceSheet: string, sourceCell: string, sourceLabel: string): FieldSource => ({
  sourceSheet,
  sourceCell,
  sourceLabel,
});

export const fieldSources: Record<string, FieldSource> = {
  projectName: source("ProjectSetup02", "U8", "نام پروژه"),
  companyName: source("ProjectSetup02", "U9", "نام شرکت / کارفرما"),
  industry: source("ProjectSetup02", "U10", "صنعت اصلی"),
  subIndustry: source("ProjectSetup02", "U11", "زیرصنعت"),
  projectType: source("ProjectSetup02", "U12", "نوع پروژه"),
  province: source("ProjectSetup02", "U13", "استان"),
  city: source("ProjectSetup02", "U14", "شهر"),
  baseYear: source("ProjectSetup02", "U25", "سال پایه"),
  constructionStartDate: source("ProjectSetup02", "U27", "شروع ساخت"),
  operationStartDate: source("ProjectSetup02", "U28", "شروع بهره‌برداری"),
  constructionDurationMonths: source("ProjectSetup02", "U29", "مدت ساخت"),
  modelHorizonYears: source("ProjectSetup02", "U31", "عمر طرح"),
  inflationRate: source("MarcoAssumptions05", "V19", "تورم عمومی سالانه"),
  salesPriceGrowth: source("MarcoAssumptions05", "V20", "رشد قیمت فروش"),
  discountRate: source("DCF-Valuation17", "R10", "نرخ تنزیل پایه"),
  terminalGrowthRate: source("DCF-Valuation17", "R12", "نرخ رشد بلندمدت"),
  corporateTaxRate: source("MarcoAssumptions05", "V47", "نرخ مالیات بر درآمد"),
  freeMarketFx: source("MarcoAssumptions05", "V34", "نرخ ارز آزاد"),
  targetMarketShare: source("MarketDemand08", "Q21", "سهم هدف"),
  salesGrowthRate: source("MarketDemand08", "Q48", "نرخ رشد فروش"),
  baseSalesPrice: source("MarketDemand08", "Q52", "نرخ فروش هر واحد"),
  nominalCapacity: source("CapacityProduction09", "Q7", "ظرفیت اسمی طراحی"),
  utilizationYear1: source("CapacityProduction09", "Q20", "ضریب بهره‌برداری سال اول"),
  yieldRate: source("CapacityProduction09", "Q24", "راندمان تولید"),
  directLaborUnitCost: source("COGS-DirectCost10", "Q22", "دستمزد مستقیم تولید"),
  totalOpex: source("Opex-Indirect11", "Q50", "کل هزینه‌های غیرمستقیم سالانه"),
  totalCapex: source("Capex12", "U94", "کل سرمایه‌گذاری ثابت"),
  workingCapital: source("WorkingCapital13", "R34", "سرمایه در گردش خالص"),
  equity: source("Financing14", "R8", "آورده سهامدار"),
  longTermDebt: source("Financing14", "R10", "وام بلندمدت"),
  interestRate: source("Financing14", "R12", "نرخ سود وام"),
  gracePeriodYears: source("Financing14", "R11", "تنفس"),
  repaymentYears: source("Financing14", "R15", "مدت بازپرداخت"),
  constructionTotalOutflow: source("ConstructionCashFlow", "U76", "کل خروج نقدی فاز توسعه"),
  npv: source("DCF-Valuation17", "R42", "NPV"),
  irr: source("DCF-Valuation17", "R43", "IRR"),
  payback: source("DCF-Valuation17", "R45", "Payback"),
  minDscr: source("DashboardBank22", "T31", "حداقل DSCR"),
};

export const excelDiagnostics = [
  {
    id: "excel-readme-empty",
    severity: "info" as const,
    module: "methodology",
    message: "ReadMe01 در workbook خالی است؛ متن راهنما در اپ از Markdown محصول ساخته شده است.",
    sourceSheet: "ReadMe01",
    sourceCell: "A1",
  },
  {
    id: "excel-methodology-sparse",
    severity: "warning" as const,
    module: "methodology",
    message: "MethodologyMap03 فقط عنوان و توضیح دارد؛ دیکشنری فرمول و flow graph در کد با mapping آماده تکمیل شده است.",
    sourceSheet: "MethodologyMap03",
    sourceCell: "Q3",
  },
  {
    id: "excel-broken-named-ranges",
    severity: "warning" as const,
    module: "master-data",
    message: "دو named range با #REF! در workbook پیدا شد: «نوع» و «نوع_وثیقه».",
    sourceSheet: "MasterData04",
    sourceCell: "#REF!",
  },
  {
    id: "excel-tax-year20-na",
    severity: "warning" as const,
    module: "capex",
    message: "ردیف سال ۲۰ در TaxDepreciation15 مقدار cache شده نامعتبر دارد؛ engine وب جدول مالیات CAPEX را بدون خطای نمایشی تولید می‌کند.",
    sourceSheet: "TaxDepreciation15",
    sourceCell: "H73",
  },
  {
    id: "excel-mirr-input",
    severity: "warning" as const,
    module: "valuation",
    message: "فرمول MIRR در DCF-Valuation17 از سلول متنی نوع تحلیل استفاده کرده است؛ engine وب نرخ finance/reinvestment عددی را به کار می‌برد.",
    sourceSheet: "DCF-Valuation17",
    sourceCell: "R44",
  },
];
