import type { ModuleSlug } from "@/lib/types";

export type FieldConfig = {
  label: string;
  path: string;
  type: "text" | "number" | "percent" | "date" | "select" | "boolean";
  source?: string;
  options?: string[];
  help?: string;
};

export type KpiConfig = {
  id: string;
  label: string;
  valuePath: string;
  type: "money" | "number" | "percent";
  traceId?: string;
};

export type ModuleConfig = {
  slug: ModuleSlug;
  title: string;
  eyebrow: string;
  group: string;
  route: string;
  sheet: string;
  status: "complete" | "warning" | "readonly" | "draft";
  description: string;
  basicGuide: string;
  fields: FieldConfig[];
  kpis: KpiConfig[];
  advanced: "generic" | "financials" | "valuation" | "financing" | "construction" | "sensitivity" | "montecarlo" | "dashboard" | "report" | "methodology" | "masterdata";
};

const money = (id: string, label: string, valuePath: string, traceId?: string): KpiConfig => ({ id, label, valuePath, type: "money", traceId });
const number = (id: string, label: string, valuePath: string, traceId?: string): KpiConfig => ({ id, label, valuePath, type: "number", traceId });
const percent = (id: string, label: string, valuePath: string, traceId?: string): KpiConfig => ({ id, label, valuePath, type: "percent", traceId });

export const moduleConfigs: ModuleConfig[] = [
  {
    slug: "overview",
    title: "نمای کلی پروژه",
    eyebrow: "Project Overview",
    group: "شروع و مدیریت پروژه",
    route: "/overview",
    sheet: "DashboardExecutive21",
    status: "warning",
    description: "نمای یکپارچه امکان‌سنجی، ارزش‌گذاری، بانک‌پذیری و ریسک.",
    basicGuide: "در این صفحه وضعیت کلی پروژه را می‌بینید و می‌توانید از روی KPIها وارد جزئیات هر ماژول شوید.",
    fields: [],
    kpis: [
      money("npv", "NPV", "valuation.npv", "valuation.npv"),
      percent("irr", "IRR", "valuation.irr", "valuation.npv"),
      number("payback", "Payback", "valuation.payback", "valuation.npv"),
      number("minDscr", "حداقل DSCR", "financing.minimumDscr", "financing.fixedPayment"),
      money("capex", "کل CAPEX", "capex.totalCapex", "capex.total"),
      money("debt", "وام", "financing.totalDebtService", "financing.fixedPayment"),
    ],
    advanced: "dashboard",
  },
  {
    slug: "setup",
    title: "تنظیمات پایه پروژه",
    eyebrow: "Project Setup",
    group: "شروع و مدیریت پروژه",
    route: "/setup",
    sheet: "ProjectSetup02",
    status: "complete",
    description: "هویت پروژه، تاریخ‌ها، افق مدل، واحد پول و مخاطب گزارش.",
    basicGuide: "این فرم پایه تمام محاسبات است. تغییر تاریخ‌ها و افق مدل فوراً state را به‌روزرسانی می‌کند و با Run Calculation خروجی‌ها عوض می‌شوند.",
    fields: [
      { label: "نام پروژه", path: "project.name", type: "text", source: "ProjectSetup02!U8" },
      { label: "نام شرکت", path: "project.companyName", type: "text", source: "ProjectSetup02!U9" },
      { label: "صنعت", path: "project.industry", type: "select", options: ["انرژی", "تولید", "خدمات", "نرم‌افزار/SaaS", "زیرساخت"], source: "ProjectSetup02!U10" },
      { label: "زیرصنعت", path: "project.subIndustry", type: "text", source: "ProjectSetup02!U11" },
      { label: "استان", path: "project.province", type: "text", source: "ProjectSetup02!U13" },
      { label: "شهر", path: "project.city", type: "text", source: "ProjectSetup02!U14" },
      { label: "سال پایه", path: "project.baseYear", type: "number", source: "ProjectSetup02!U25" },
      { label: "شروع ساخت", path: "project.constructionStartDate", type: "date", source: "ProjectSetup02!U27" },
      { label: "شروع بهره‌برداری", path: "project.operationStartDate", type: "date", source: "ProjectSetup02!U28" },
      { label: "مدت ساخت (ماه)", path: "project.constructionDurationMonths", type: "number", source: "ProjectSetup02!U29" },
      { label: "افق مدل (سال)", path: "project.modelHorizonYears", type: "number", source: "ProjectSetup02!U31" },
      { label: "واحد نمایش", path: "project.displayUnit", type: "select", options: ["rial", "million-rial", "billion-rial"], source: "ProjectSetup02!U36" },
    ],
    kpis: [number("horizon", "افق مدل", "project.modelHorizonYears"), number("duration", "مدت ساخت", "project.constructionDurationMonths")],
    advanced: "generic",
  },
  {
    slug: "methodology",
    title: "روش‌شناسی و نقشه فرمول",
    eyebrow: "Methodology Map",
    group: "شروع و مدیریت پروژه",
    route: "/methodology",
    sheet: "MethodologyMap03",
    status: "readonly",
    description: "flow محاسباتی، dictionary فرمول‌ها، mapping به Excel و diagnostics.",
    basicGuide: "این صفحه خواندنی است و توضیح می‌دهد هر خروجی از چه ورودی و فرمولی ساخته می‌شود.",
    fields: [],
    kpis: [number("traceCount", "Trace فعال", "traces.length"), number("validationCount", "Issue", "validations.length")],
    advanced: "methodology",
  },
  {
    slug: "master-data",
    title: "داده‌های پایه",
    eyebrow: "Master Data",
    group: "شروع و مدیریت پروژه",
    route: "/master-data",
    sheet: "MasterData04",
    status: "warning",
    description: "لیست‌های قابل توسعه برای صنعت، ارز، نوع وام، روش بازپرداخت، دارایی و سناریو.",
    basicGuide: "در این نسخه لیست‌های اصلی قابل مشاهده و بخشی از گزینه‌ها در فرم‌ها قابل ویرایش هستند.",
    fields: [],
    kpis: [number("sheets", "شیت‌های mapped", "excelSheets.length"), number("broken", "Named range خراب", "diagnostics.brokenNamedRanges")],
    advanced: "masterdata",
  },
  {
    slug: "macro",
    title: "مفروضات کلان و نرخ ارز",
    eyebrow: "Macro & FX",
    group: "شروع و مدیریت پروژه",
    route: "/macro",
    sheet: "MarcoAssumptions05",
    status: "complete",
    description: "تورم، رشد قیمت، مالیات، نرخ تنزیل و نرخ‌های چندگانه ارز.",
    basicGuide: "چند نرخ کلیدی را در Basic تنظیم کنید؛ Advanced همه نرخ‌های FX و مالیاتی را نشان می‌دهد.",
    fields: [
      { label: "تورم عمومی", path: "assumptions.macro.inflationRate", type: "percent", source: "MarcoAssumptions05!V19" },
      { label: "رشد قیمت فروش", path: "assumptions.macro.salesPriceGrowth", type: "percent", source: "MarcoAssumptions05!V20" },
      { label: "رشد دستمزد", path: "assumptions.macro.wageGrowth", type: "percent", source: "MarcoAssumptions05!V21" },
      { label: "رشد OPEX", path: "assumptions.macro.opexGrowth", type: "percent", source: "MarcoAssumptions05!V26" },
      { label: "مالیات شرکت", path: "assumptions.macro.corporateTaxRate", type: "percent", source: "MarcoAssumptions05!V47" },
      { label: "نرخ تنزیل", path: "assumptions.macro.discountRate", type: "percent", source: "DCF-Valuation17!R10" },
      { label: "رشد پایانی", path: "assumptions.macro.terminalGrowthRate", type: "percent", source: "DCF-Valuation17!R12" },
      { label: "نرخ ارز آزاد", path: "assumptions.macro.fxRates.freeMarket", type: "number", source: "MarcoAssumptions05!V34" },
    ],
    kpis: [percent("discount", "نرخ تنزیل", "assumptions.macro.discountRate"), percent("tax", "مالیات", "assumptions.macro.corporateTaxRate"), number("fx", "FX آزاد", "assumptions.macro.fxRates.freeMarket")],
    advanced: "generic",
  },
  {
    slug: "scenarios",
    title: "مدیریت سناریو",
    eyebrow: "Scenario Manager",
    group: "ریسک و سناریو",
    route: "/scenarios",
    sheet: "ScenarioManager06",
    status: "draft",
    description: "سناریوی پایه، خوش‌بینانه، بدبینانه، شوک ارزی، تورمی و تأخیر اجرا.",
    basicGuide: "فعلاً سناریوی پایه editable است و ساختار برای duplicate/lock آماده شده است.",
    fields: [
      { label: "نام سناریو", path: "scenario.name", type: "text", source: "ScenarioManager06!X8" },
      { label: "توضیح", path: "scenario.description", type: "text", source: "ScenarioManager06!U54" },
      { label: "قفل سناریو", path: "scenario.isLocked", type: "boolean", source: "ProjectSetup02!U50" },
    ],
    kpis: [number("scenarios", "سناریوها", "project.scenarios.length"), percent("risk", "ریسک مجاز", "assumptions.macro.projectRiskPremium")],
    advanced: "generic",
  },
  {
    slug: "industry-template",
    title: "قالب صنعت",
    eyebrow: "Industry Template",
    group: "بازار و عملیات",
    route: "/industry-template",
    sheet: "IndustryTemplate07",
    status: "complete",
    description: "پیش‌فرض‌های صنعت انرژی خورشیدی، وابستگی ارزی، مجوز و ریسک.",
    basicGuide: "قالب صنعت رفتار ظرفیت، هزینه و ریسک را برای مدل ساده‌تر می‌کند.",
    fields: [
      { label: "مدل کسب‌وکار", path: "assumptions.industry.businessModel", type: "text", source: "IndustryTemplate07!R10" },
      { label: "شدت سرمایه‌بری", path: "assumptions.industry.capitalIntensity", type: "select", options: ["پایین", "متوسط", "بالا"], source: "IndustryTemplate07!R14" },
      { label: "سهم هزینه وارداتی", path: "assumptions.industry.importedCostShare", type: "percent", source: "IndustryTemplate07!R61" },
      { label: "ریسک ارزی", path: "assumptions.industry.fxRisk", type: "select", options: ["پایین", "متوسط", "بالا"], source: "IndustryTemplate07!R54" },
    ],
    kpis: [percent("imported", "وابستگی واردات", "assumptions.industry.importedCostShare"), percent("gov", "وابستگی تعرفه", "assumptions.industry.governmentTariffDependence")],
    advanced: "generic",
  },
  {
    slug: "market-demand",
    title: "بازار و تقاضا",
    eyebrow: "Market Demand",
    group: "بازار و عملیات",
    route: "/market-demand",
    sheet: "MarketDemand08",
    status: "complete",
    description: "TAM/SAM/SOM، سهم بازار، قیمت فروش و تقاضای قابل تحقق.",
    basicGuide: "حجم بازار، قیمت و سقف فروش را تنظیم کنید؛ درآمد از همین صفحه و ظرفیت تولید ساخته می‌شود.",
    fields: [
      { label: "اندازه کل بازار", path: "assumptions.market.totalMarketSize", type: "number", source: "MarketDemand08!Q18" },
      { label: "بازار قابل دسترس", path: "assumptions.market.addressableMarket", type: "number", source: "MarketDemand08!Q19" },
      { label: "بازار هدف", path: "assumptions.market.targetMarket", type: "number", source: "MarketDemand08!Q20" },
      { label: "سهم هدف", path: "assumptions.market.targetMarketShare", type: "percent", source: "MarketDemand08!Q21" },
      { label: "رشد فروش", path: "assumptions.market.salesGrowthRate", type: "percent", source: "MarketDemand08!Q48" },
      { label: "سقف فروش", path: "assumptions.market.demandLimit", type: "number", source: "MarketDemand08!Q50" },
      { label: "قیمت فروش واحد", path: "assumptions.market.baseSalesPrice", type: "number", source: "MarketDemand08!Q52" },
    ],
    kpis: [money("revenue", "درآمد سال ۱", "statements.rows.1.revenue", "revenue.year1"), number("volume", "حجم فروش سال ۱", "statements.rows.1.salesVolume"), number("price", "قیمت فروش", "assumptions.market.baseSalesPrice")],
    advanced: "generic",
  },
  {
    slug: "capacity-production",
    title: "ظرفیت و تولید",
    eyebrow: "Capacity Production",
    group: "بازار و عملیات",
    route: "/capacity-production",
    sheet: "CapacityProduction09",
    status: "complete",
    description: "ظرفیت طراحی، ساعات موثر، downtime، yield و ramp-up.",
    basicGuide: "ظرفیت موثر تولید، سقف عملی فروش را کنترل می‌کند.",
    fields: [
      { label: "ظرفیت اسمی", path: "assumptions.capacity.nominalCapacity", type: "number", source: "CapacityProduction09!Q7" },
      { label: "روز کاری", path: "assumptions.capacity.workingDaysPerYear", type: "number", source: "CapacityProduction09!Q15" },
      { label: "ساعت موثر شیفت", path: "assumptions.capacity.effectiveHoursPerShift", type: "number", source: "CapacityProduction09!Q17" },
      { label: "بهره‌برداری سال اول", path: "assumptions.capacity.utilizationYear1", type: "percent", source: "CapacityProduction09!Q20" },
      { label: "بهره‌برداری پایدار", path: "assumptions.capacity.utilizationStable", type: "percent", source: "CapacityProduction09!Q22" },
      { label: "راندمان", path: "assumptions.capacity.yieldRate", type: "percent", source: "CapacityProduction09!Q24" },
    ],
    kpis: [number("capacity", "ظرفیت موثر اسمی", "capacity.effectiveNominalCapacity", "capacity.effectiveNominalCapacity"), number("production", "تولید سال ۱", "capacity.rows.1.productionVolume"), percent("util", "بهره‌برداری", "capacity.rows.1.utilization")],
    advanced: "generic",
  },
  {
    slug: "revenue",
    title: "درآمد",
    eyebrow: "Revenue",
    group: "بازار و عملیات",
    route: "/revenue",
    sheet: "MarketDemand08",
    status: "complete",
    description: "درآمد از اتصال تقاضا، ظرفیت، قیمت و رشد ساخته می‌شود.",
    basicGuide: "درآمد تولیدی است اما ورودی‌های قیمت، سهم بازار و سقف فروش editable هستند.",
    fields: [
      { label: "قیمت فروش واحد", path: "assumptions.market.baseSalesPrice", type: "number", source: "MarketDemand08!Q52" },
      { label: "رشد قیمت", path: "assumptions.market.priceGrowthRate", type: "percent", source: "MarcoAssumptions05!V20" },
      { label: "رشد فروش", path: "assumptions.market.salesGrowthRate", type: "percent", source: "MarketDemand08!Q48" },
      { label: "سهم صادرات", path: "assumptions.market.exportShare", type: "percent" },
    ],
    kpis: [money("revenue", "درآمد سال ۱", "statements.rows.1.revenue", "revenue.year1"), percent("margin", "Gross Margin", "statements.rows.1.grossMargin"), money("year5", "درآمد سال ۵", "statements.rows.5.revenue")],
    advanced: "generic",
  },
  {
    slug: "direct-costs",
    title: "هزینه‌های مستقیم",
    eyebrow: "COGS Direct Cost",
    group: "بازار و عملیات",
    route: "/direct-costs",
    sheet: "COGS-DirectCost10",
    status: "complete",
    description: "مدل unit cost یا درصدی برای مواد، انرژی و دستمزد مستقیم.",
    basicGuide: "روش هزینه را انتخاب کنید و اقلام اصلی واحد را تغییر دهید.",
    fields: [
      { label: "روش COGS", path: "assumptions.directCosts.method", type: "select", options: ["unitCost", "percentOfRevenue"], source: "COGS-DirectCost10!Q14" },
      { label: "درصد از درآمد", path: "assumptions.directCosts.cogsPercent", type: "percent" },
      { label: "دستمزد مستقیم واحد", path: "assumptions.directCosts.directLaborUnitCost", type: "number", source: "COGS-DirectCost10!Q22" },
      { label: "هزینه انرژی واحد", path: "assumptions.directCosts.energyUnitCost", type: "number", source: "COGS-DirectCost10!Q21" },
      { label: "سهم ارزی مواد", path: "assumptions.directCosts.rawMaterialFxShare", type: "percent", source: "COGS-DirectCost10!Q18" },
    ],
    kpis: [money("cogs", "COGS سال ۱", "statements.rows.1.cogs", "directCosts.year1"), percent("gm", "Gross Margin", "statements.rows.1.grossMargin"), number("unit", "Unit Cost", "directCosts.rows.1.unitCost")],
    advanced: "generic",
  },
  {
    slug: "opex",
    title: "OPEX",
    eyebrow: "Opex Indirect",
    group: "بازار و عملیات",
    route: "/opex",
    sheet: "Opex-Indirect11",
    status: "complete",
    description: "حقوق، بیمه، اجاره، IT، بازاریابی و سایر هزینه‌های عملیاتی.",
    basicGuide: "OPEX پایه و رشد را تنظیم کنید؛ EBITDA از همین خروجی و درآمد ساخته می‌شود.",
    fields: [
      { label: "حقوق اداری", path: "assumptions.opex.salaries", type: "number", source: "Opex-Indirect11!Q20" },
      { label: "بیمه کارفرما", path: "assumptions.opex.employerInsuranceRate", type: "percent", source: "Opex-Indirect11!Q21" },
      { label: "اجاره", path: "assumptions.opex.rent", type: "number", source: "Opex-Indirect11!Q23" },
      { label: "IT", path: "assumptions.opex.it", type: "number", source: "Opex-Indirect11!Q26" },
      { label: "رشد هر قلم", path: "assumptions.opex.growthRate", type: "percent", source: "Opex-Indirect11!Q43" },
      { label: "سهم ارزی OPEX", path: "assumptions.opex.fxShare", type: "percent", source: "Opex-Indirect11!Q56" },
    ],
    kpis: [money("opex1", "OPEX سال ۱", "statements.rows.1.opex", "opex.year1"), money("ebitda", "EBITDA سال ۱", "statements.rows.1.ebitda", "statements.ebitda.year1"), percent("share", "OPEX/Revenue", "opex.rows.1.totalOpex")],
    advanced: "generic",
  },
  {
    slug: "capex",
    title: "CAPEX و دارایی ثابت",
    eyebrow: "Capex",
    group: "سرمایه‌گذاری و ساخت",
    route: "/capex",
    sheet: "Capex12",
    status: "complete",
    description: "اقلام سرمایه‌گذاری، پرداخت مرحله‌ای، تأخیر، احتیاط و استهلاک.",
    basicGuide: "قیمت، مقدار، contingency و زمان‌بندی پرداخت CAPEX را ویرایش کنید.",
    fields: [
      { label: "نام قلم", path: "assumptions.capex.items.0.name", type: "text", source: "Capex12!U9" },
      { label: "مقدار", path: "assumptions.capex.items.0.quantity", type: "number", source: "Capex12!U20" },
      { label: "قیمت واحد", path: "assumptions.capex.items.0.unitPrice", type: "number", source: "Capex12!U21" },
      { label: "افزایش قیمت", path: "assumptions.capex.items.0.priceIncreaseRate", type: "percent", source: "Capex12!U25" },
      { label: "پیش‌پرداخت", path: "assumptions.capex.items.0.prepaymentRate", type: "percent", source: "Capex12!U38" },
      { label: "پرداخت تحویل", path: "assumptions.capex.items.0.deliveryPaymentRate", type: "percent", source: "Capex12!U39" },
      { label: "پس از نصب", path: "assumptions.capex.items.0.postInstallPaymentRate", type: "percent", source: "Capex12!U40" },
      { label: "Contingency", path: "assumptions.capex.items.0.contingencyRate", type: "percent", source: "Capex12!U56" },
    ],
    kpis: [money("total", "کل CAPEX", "capex.totalCapex", "capex.total"), money("delay", "هزینه تأخیر", "capex.delayCost", "capex.total"), money("dep", "استهلاک سال ۱", "capex.annual.1.depreciation")],
    advanced: "generic",
  },
  {
    slug: "construction-cashflow",
    title: "جریان نقدی فاز ساخت",
    eyebrow: "Construction Cash Flow",
    group: "سرمایه‌گذاری و ساخت",
    route: "/construction-cashflow",
    sheet: "ConstructionCashFlow",
    status: "complete",
    description: "مرکز کنترل ماهانه پرداخت CAPEX، هزینه‌های ساخت، تأخیر، منابع نقدینگی، خط اعتباری و هشدارهای Cash Crunch.",
    basicGuide: "در این مسیر guided همان مدل کامل فاز ساخت را با ورودی‌های ساده‌شده می‌بینید: زمان‌بندی CAPEX، هزینه‌ها، تأخیر، منابع و هشدارهای نقدینگی همه editable هستند.",
    fields: [
      { label: "حقوق ماهانه تیم توسعه", path: "assumptions.construction.monthlyDevelopmentPayroll", type: "number", source: "ConstructionCashFlow!U31" },
      { label: "پیمانکار/مشاور ماهانه", path: "assumptions.construction.monthlyContractorCost", type: "number", source: "ConstructionCashFlow!U32" },
      { label: "زیرساخت ماهانه", path: "assumptions.construction.monthlyInfrastructureCost", type: "number", source: "ConstructionCashFlow!U33" },
      { label: "تست/امنیت ماهانه", path: "assumptions.construction.monthlyTestingCost", type: "number", source: "ConstructionCashFlow!U34" },
      { label: "خط اعتباری فعال", path: "assumptions.construction.creditLineEnabled", type: "boolean", source: "ConstructionCashFlow!U42" },
    ],
    kpis: [money("outflow", "کل خروجی ساخت", "construction.kpis.totalCashOutflow", "construction.cashCrunch"), number("crunch", "ماه‌های Cash Crunch", "construction.kpis.cashCrunchMonths"), money("credit", "نیاز خط اعتباری", "construction.creditLineRequired")],
    advanced: "construction",
  },
  {
    slug: "working-capital",
    title: "سرمایه در گردش",
    eyebrow: "Working Capital",
    group: "سرمایه‌گذاری و ساخت",
    route: "/working-capital",
    sheet: "WorkingCapital13",
    status: "complete",
    description: "مطالبات، موجودی، پیش‌پرداخت، پرداختنی و نقد احتیاطی.",
    basicGuide: "روزهای وصول، موجودی و پرداخت را تغییر دهید؛ اثر آن روی FCFF و DSCR دیده می‌شود.",
    fields: [
      { label: "روز وصول مطالبات", path: "assumptions.workingCapital.receivableDays", type: "number", source: "WorkingCapital13!R10" },
      { label: "روز موجودی کالا", path: "assumptions.workingCapital.inventoryDays", type: "number", source: "WorkingCapital13!R9" },
      { label: "دوره پرداخت به تامین‌کنندگان", path: "assumptions.workingCapital.payableDays", type: "number", source: "WorkingCapital13!R11" },
      { label: "روز نقد احتیاطی", path: "assumptions.workingCapital.minimumCashDays", type: "number", source: "WorkingCapital13!R13" },
      { label: "آزادسازی در سال آخر", path: "assumptions.workingCapital.releaseInFinalYear", type: "boolean", source: "WorkingCapital13!R40" },
    ],
    kpis: [money("initial", "WC سال ۱", "workingCapital.initialWorkingCapital", "workingCapital.year1"), money("release", "آزادسازی نهایی", "workingCapital.releaseFinalYear"), money("delta", "تغییر WC سال ۱", "workingCapital.rows.1.changeInWorkingCapital")],
    advanced: "generic",
  },
  {
    slug: "financing",
    title: "تأمین مالی",
    eyebrow: "Financing",
    group: "تأمین مالی و مالیات",
    route: "/financing",
    sheet: "Financing14",
    status: "warning",
    description: "آورده، وام، نرخ، تنفس، روش بازپرداخت، DSCR و سیاست تقسیم سود.",
    basicGuide: "ساختار بدهی و آورده این فایل بسیار سنگین است؛ DSCR پایین را در همین صفحه می‌بینید.",
    fields: [
      { label: "آورده سهامدار", path: "assumptions.financing.equity", type: "number", source: "Financing14!R8" },
      { label: "وام بلندمدت", path: "assumptions.financing.longTermDebt", type: "number", source: "Financing14!R10" },
      { label: "تنفس", path: "assumptions.financing.gracePeriodYears", type: "number", source: "Financing14!R11" },
      { label: "نرخ سود وام", path: "assumptions.financing.interestRate", type: "percent", source: "Financing14!R12" },
      { label: "کارمزد", path: "assumptions.financing.feeRate", type: "percent", source: "Financing14!R13" },
      { label: "روش بازپرداخت", path: "assumptions.financing.repaymentMethod", type: "select", options: ["قسط ثابت", "اصل مساوی", "سود فقط سپس اصل در سررسید", "یکجا در سررسید"], source: "Financing14!R14" },
      { label: "مدت بازپرداخت", path: "assumptions.financing.repaymentYears", type: "number", source: "Financing14!R15" },
    ],
    kpis: [number("minDscr", "حداقل DSCR", "financing.minimumDscr", "financing.fixedPayment"), money("interest", "کل هزینه مالی", "financing.kpis.totalProjectFinancingCost"), money("service", "کل Debt Service", "financing.totalDebtService")],
    advanced: "financing",
  },
  {
    slug: "financial-statements",
    title: "صورت‌های مالی",
    eyebrow: "Financial Statements",
    group: "خروجی‌های مالی",
    route: "/financial-statements",
    sheet: "FinancialStatements16",
    status: "warning",
    description: "صورت سود و زیان، ترازنامه، جریان نقد، نسبت‌ها و کنترل‌ها از سال ۰ تا ۲۰.",
    basicGuide: "Basic خلاصه سه صورت مالی را می‌دهد؛ Advanced جدول سالانه کامل با سلول‌های محاسباتی قفل‌شده است.",
    fields: [],
    kpis: [money("rev", "درآمد سال ۱", "statements.rows.1.revenue", "revenue.year1"), money("ebitda", "EBITDA سال ۱", "statements.rows.1.ebitda", "statements.ebitda.year1"), money("cash", "نقد پایان سال ۱", "statements.rows.1.cash"), money("balance", "Balance Check سال ۱", "statements.rows.1.balanceCheck")],
    advanced: "financials",
  },
  {
    slug: "valuation",
    title: "ارزش‌گذاری DCF",
    eyebrow: "DCF Valuation",
    group: "خروجی‌های مالی",
    route: "/valuation",
    sheet: "DCF-Valuation17",
    status: "warning",
    description: "FCFF، NPV، IRR، MIRR، Payback، Terminal Value و diagnostics.",
    basicGuide: "IRR و Payback از سری خام FCFF حساب می‌شوند؛ اگر قابل محاسبه نباشند دلیل نمایش داده می‌شود.",
    fields: [
      { label: "نرخ تنزیل", path: "assumptions.macro.discountRate", type: "percent", source: "DCF-Valuation17!R10" },
      { label: "رشد پایانی", path: "assumptions.macro.terminalGrowthRate", type: "percent", source: "DCF-Valuation17!R12" },
      { label: "نرخ بازسرمایه‌گذاری", path: "assumptions.macro.reinvestmentRate", type: "percent", source: "DCF-Valuation17!R16" },
      { label: "نرخ تأمین مالی MIRR", path: "assumptions.macro.financeRate", type: "percent", source: "DCF-Valuation17!R17" },
    ],
    kpis: [money("npv", "NPV", "valuation.npv", "valuation.npv"), percent("irr", "IRR", "valuation.irr", "valuation.npv"), percent("mirr", "MIRR", "valuation.mirr", "valuation.npv"), number("payback", "Payback", "valuation.payback", "valuation.npv")],
    advanced: "valuation",
  },
  {
    slug: "economic-analysis",
    title: "تحلیل اقتصادی",
    eyebrow: "Economic Analysis",
    group: "خروجی‌های مالی",
    route: "/economic-analysis",
    sheet: "EconomicAnalysis18",
    status: "complete",
    description: "ENPV، EIRR، ارزش افزوده، سایه‌قیمت‌ها و منافع اجتماعی.",
    basicGuide: "تحلیل اقتصادی مالی را به قیمت سایه و منافع اجتماعی وصل می‌کند.",
    fields: [
      { label: "نرخ تنزیل اقتصادی", path: "assumptions.economic.economicDiscountRate", type: "percent", source: "EconomicAnalysis18!R9" },
      { label: "SCF", path: "assumptions.economic.standardConversionFactor", type: "number", source: "EconomicAnalysis18!R10" },
      { label: "SERF", path: "assumptions.economic.shadowExchangeRateFactor", type: "number", source: "EconomicAnalysis18!R13" },
      { label: "منفعت اشتغال مستقیم", path: "assumptions.economic.directEmploymentBenefit", type: "number", source: "EconomicAnalysis18!R52" },
    ],
    kpis: [money("enpv", "ENPV", "economic.enpv"), percent("eirr", "EIRR", "economic.eirr"), money("va", "Value Added", "economic.valueAdded")],
    advanced: "generic",
  },
  {
    slug: "sensitivity",
    title: "تحلیل حساسیت",
    eyebrow: "Sensitivity",
    group: "ریسک و سناریو",
    route: "/sensitivity",
    sheet: "Sensivity19",
    status: "complete",
    description: "تحلیل یک‌طرفه، دوطرفه، tornado و آستانه شکست.",
    basicGuide: "متغیرهای حساس را انتخاب کنید و اثر روی NPV/IRR/DSCR را ببینید.",
    fields: [
      { label: "شاخص", path: "assumptions.sensitivity.selectedMetric", type: "select", options: ["NPV", "IRR", "Payback", "DSCR"], source: "Sensivity19!U8" },
      { label: "متغیر ۱", path: "assumptions.sensitivity.variable1", type: "select", options: ["فروش", "هزینه", "CAPEX", "نرخ ارز", "نرخ تنزیل", "نرخ بهره", "تاخیر"], source: "Sensivity19!T24" },
      { label: "متغیر ۲", path: "assumptions.sensitivity.variable2", type: "select", options: ["هزینه", "فروش", "CAPEX", "نرخ ارز", "نرخ تنزیل", "نرخ بهره", "تاخیر"], source: "Sensivity19!T41" },
    ],
    kpis: [money("low", "خروجی حد پایین", "sensitivity.oneWay.0.metric"), money("base", "خروجی مبنا", "sensitivity.oneWay.1.metric"), money("high", "خروجی حد بالا", "sensitivity.oneWay.2.metric")],
    advanced: "sensitivity",
  },
  {
    slug: "monte-carlo",
    title: "مونت‌کارلو",
    eyebrow: "Monte Carlo",
    group: "ریسک و سناریو",
    route: "/monte-carlo",
    sheet: "MonteCarlo20",
    status: "draft",
    description: "شبیه‌سازی ریسک NPV، نقدینگی و DSCR با توزیع‌های احتمال.",
    basicGuide: "شبیه‌سازی IRR فقط وقتی سری کامل جریان نقد تولید و تغییر علامت معتبر داشته باشد گزارش می‌شود.",
    fields: [
      { label: "فعال بودن", path: "assumptions.monteCarlo.enabled", type: "boolean", source: "MonteCarlo20!T9" },
      { label: "تعداد تکرار", path: "assumptions.monteCarlo.iterations", type: "number", source: "MonteCarlo20!T12" },
      { label: "Seed", path: "assumptions.monteCarlo.seed", type: "number", source: "MonteCarlo20!T13" },
    ],
    kpis: [money("p5", "P5 NPV", "monteCarlo.p5"), money("p50", "P50 NPV", "monteCarlo.p50"), money("p95", "P95 NPV", "monteCarlo.p95"), percent("prob", "احتمال NPV مثبت", "monteCarlo.probabilityNpvPositive")],
    advanced: "montecarlo",
  },
  {
    slug: "dashboard-executive",
    title: "داشبورد اجرایی",
    eyebrow: "Executive Dashboard",
    group: "داشبوردها",
    route: "/dashboard/executive",
    sheet: "DashboardExecutive21",
    status: "warning",
    description: "تصمیم سرمایه‌گذاری، روندها، ریسک‌ها و سناریو.",
    basicGuide: "این داشبورد برای مدیرعامل/سرمایه‌گذار طراحی شده است.",
    fields: [],
    kpis: [number("health", "Project Health", "dashboards.projectHealthScore"), number("ready", "Investment Readiness", "dashboards.investmentReadinessScore"), money("npv", "NPV", "valuation.npv")],
    advanced: "dashboard",
  },
  {
    slug: "dashboard-bank",
    title: "داشبورد بانک",
    eyebrow: "Bank Dashboard",
    group: "داشبوردها",
    route: "/dashboard/bank",
    sheet: "DashboardBank22",
    status: "warning",
    description: "DSCR، بدهی، پوشش وثیقه، cash crunch و تصمیم بانک.",
    basicGuide: "تمرکز این صفحه روی قابلیت ارائه به بانک است.",
    fields: [],
    kpis: [number("bank", "Bankability", "dashboards.bankabilityScore"), number("minDscr", "حداقل DSCR", "financing.minimumDscr"), number("target", "DSCR هدف", "assumptions.financing.targetDscr")],
    advanced: "dashboard",
  },
  {
    slug: "dashboard-management",
    title: "داشبورد مدیریت",
    eyebrow: "Management Dashboard",
    group: "داشبوردها",
    route: "/dashboard/management",
    sheet: "DashboardManagement23",
    status: "complete",
    description: "فروش، ظرفیت، OPEX، COGS، نقد و هشدارهای عملیاتی.",
    basicGuide: "این صفحه برای مدیریت عملیات و کنترل فرضیات روزانه است.",
    fields: [],
    kpis: [money("sales", "فروش سال جاری", "statements.rows.1.revenue"), percent("util", "استفاده ظرفیت", "capacity.rows.1.utilization"), money("cash", "نقد", "statements.rows.1.cash")],
    advanced: "dashboard",
  },
  {
    slug: "report",
    title: "گزارش‌ساز",
    eyebrow: "Report Pack",
    group: "گزارش و خروجی",
    route: "/report",
    sheet: "ReportPack24",
    status: "draft",
    description: "قالب گزارش بانک، سرمایه‌گذار، هیئت‌مدیره، مدیریتی و خلاصه یک‌صفحه‌ای.",
    basicGuide: "متن narrative از خروجی‌ها و validation ساخته می‌شود و قابل ویرایش خواهد بود.",
    fields: [],
    kpis: [money("npv", "NPV گزارش", "valuation.npv"), number("issues", "Issues", "validations.length"), number("sections", "بخش‌ها", "report.sections")],
    advanced: "report",
  },
  {
    slug: "exports",
    title: "خروجی‌ها",
    eyebrow: "Exports",
    group: "گزارش و خروجی",
    route: "/exports",
    sheet: "ReportPack24",
    status: "draft",
    description: "Export Excel, PDF, Word, Bank Package, Investor Package و Board Pack.",
    basicGuide: "UI خروجی کامل است؛ اتصال export واقعی در فاز بعد انجام می‌شود.",
    fields: [],
    kpis: [number("formats", "فرمت‌ها", "exports.count"), number("issues", "Issue", "validations.length")],
    advanced: "report",
  },
  {
    slug: "settings",
    title: "تنظیمات",
    eyebrow: "Settings",
    group: "گزارش و خروجی",
    route: "/settings",
    sheet: "ProjectSetup02",
    status: "complete",
    description: "تنظیمات workspace، واحد نمایش، حالت Basic/Advanced و کنترل محاسبه.",
    basicGuide: "تنظیمات سرعت و نمایش از اینجا کنترل می‌شوند.",
    fields: [
      { label: "واحد نمایش", path: "project.displayUnit", type: "select", options: ["rial", "million-rial", "billion-rial"] },
      { label: "کد پروژه", path: "project.code", type: "text" },
      { label: "تهیه‌کننده", path: "project.preparedBy", type: "text" },
    ],
    kpis: [number("horizon", "افق", "project.modelHorizonYears"), number("issues", "Issue", "validations.length")],
    advanced: "generic",
  },
];

export const moduleBySlug = (slug: ModuleSlug) => moduleConfigs.find((module) => module.slug === slug)!;

export type NavigationGroup = {
  group: string;
  items: ModuleConfig[];
};

const navGroup = (group: string, slugs: ModuleSlug[]): NavigationGroup => ({
  group,
  items: slugs.map(moduleBySlug),
});

export const clientNavigationGroups: NavigationGroup[] = [
  navGroup("داشبورد", [
    "overview",
    "dashboard-executive",
    "dashboard-bank",
    "dashboard-management",
  ]),
  navGroup("پروژه و مفروضات", [
    "setup",
    "macro",
    "industry-template",
    "market-demand",
    "capacity-production",
    "direct-costs",
    "opex",
    "capex",
    "working-capital",
    "financing",
    "construction-cashflow",
  ]),
  navGroup("سناریو و ریسک", [
    "scenarios",
    "sensitivity",
    "monte-carlo",
  ]),
  navGroup("نتایج و گزارش", [
    "revenue",
    "financial-statements",
    "valuation",
    "economic-analysis",
    "report",
    "exports",
  ]),
];

const basicSlugs = new Set<ModuleSlug>([
  "overview",
  "dashboard-executive",
  "setup",
  "macro",
  "market-demand",
  "capex",
  "working-capital",
  "financing",
  "construction-cashflow",
  "scenarios",
  "valuation",
  "report",
]);

export const navigationForMode = (mode: "basic" | "advanced") =>
  clientNavigationGroups
    .map((group) => ({
      ...group,
      items: mode === "advanced" ? group.items : group.items.filter((item) => basicSlugs.has(item.slug)),
    }))
    .filter((group) => group.items.length > 0);

// Internal-only modules remain routable for model maintainers but never appear in client navigation.
export const internalModules = moduleConfigs.filter((item) =>
  item.slug === "methodology" || item.slug === "master-data" || item.slug === "settings"
);
