import type { Project, ScenarioAssumptions } from "@/lib/types";
import { calculateScenarioAdjustedAssumptions, defaultScenarioAdjustments } from "@/lib/scenario-engine";

const now = "2026-06-05T00:00:00.000Z";
const cloneAssumptions = <T,>(value: T): T => JSON.parse(JSON.stringify(value)) as T;

export const baseAssumptions: ScenarioAssumptions = {
  macro: {
    baseYear: 2026,
    analysisHorizon: 20,
    calculationBasis: "واقعی",
    fiscalYearEnd: "اسفند",
    baseCurrency: "ریال",
    activeScenarioId: "scenario-base",
    inflationGeneralAnnual: 0.2,
    inflationRate: 0.2,
    salesPriceGrowth: 0.05,
    wageGrowth: 0.15,
    energyGrowth: 0.1,
    rawMaterialGrowth: 0.08,
    servicesGrowth: 0.1,
    serviceGrowth: 0.1,
    rentGrowth: 0.08,
    assetCostGrowth: 0.1,
    opexGrowth: 0.1,
    marketingCostGrowth: 0.08,
    marketingGrowth: 0.08,
    otherCostGrowth: 0.1,
    otherGrowth: 0.1,
    officialFxRate: 380000,
    freeMarketFxRate: 500000,
    remittanceFxRate: 480000,
    baseFxRateType: "freeMarket",
    baseFxRate: 500000,
    fxConversionFactor: 1,
    fxRates: {
      official: 380000,
      freeMarket: 500000,
      nima: 480000,
      negotiated: 500000,
      persons: 500000,
      preferential: 380000,
      remittance: 480000,
      contractual: 500000,
      manual: 500000,
    },
    fxGrowthRate: 0.08,
    fxVolatility: 0.2,
    maxFxShock: 0.5,
    fxShockCap: 0.5,
    fxShockPeriod: 12,
    fxRateSource: "بازار آزاد",
    incomeTaxRate: 0.25,
    corporateTaxRate: 0.25,
    personnelInsuranceRate: 0.23,
    socialInsuranceRate: 0.23,
    vatRate: 0.1,
    customsDutyRate: 0.05,
    importDutyRate: 0.05,
    specialIndustryTaxRate: 0,
    industrySpecificTaxRate: 0,
    taxExemptionType: "ندارد",
    taxExemptionYears: 0,
    taxPenaltyRate: 0,
    insurancePenaltyRate: 0,
    regulationSource: "قوانین مالیاتی کشور",
    defaultDiscountRate: 0.2,
    discountRate: 0.2,
    costOfCapital: 0.18,
    opportunityCostOfCapital: 0.2,
    opportunityCostRate: 0.2,
    countryRiskPremium: 0.05,
    industryRiskPremium: 0.1,
    projectRiskPremium: 0.1,
    minimumSafetyMargin: 0.2,
    minimumAcceptableReturn: 0.18,
    allowedRiskLevel: "متعادل",
    analyticalNotes: "محاسبات بر اساس نرخ‌های واقعی صورت گرفته",
    terminalGrowthRate: 0.03,
    reinvestmentRate: 0.18,
    financeRate: 0.15,
    capexFxRateType: "freeMarket",
    directCostFxRateType: "freeMarket",
    opexFxRateType: "freeMarket",
    exportRevenueFxRateType: "remittance",
    financingFxRateType: "freeMarket",
    licenseFxRateType: "freeMarket",
    fxMappings: [
      { id: "fx-capex", module: "capex", label: "CAPEX ارزی", fxType: "freeMarket", source: "Capex12" },
      { id: "fx-opex", module: "opex", label: "OPEX ارزی", fxType: "freeMarket", source: "Opex-Indirect11" },
      { id: "fx-export", module: "exportRevenue", label: "درآمد صادراتی", fxType: "remittance", source: "MarketDemand08" },
      { id: "fx-financing", module: "financing", label: "LC / وام ارزی", fxType: "freeMarket", source: "Financing14" },
      { id: "fx-direct", module: "directCosts", label: "مواد اولیه وارداتی", fxType: "freeMarket", source: "COGS-DirectCost10" },
      { id: "fx-license", module: "licenses", label: "لایسنس / API / Cloud", fxType: "freeMarket", source: "Opex-Indirect11" },
    ],
  },
  industry: {
    mainIndustry: "انرژی",
    subIndustry: "نیروگاه خورشیدی",
    projectType: "انرژی",
    businessModel: "تولید برق و فروش به شبکه",
    activityType: "تولیدی",
    projectScale: "متوسط",
    targetMarket: "داخلی",
    capitalIntensity: "بالا",
    laborIntensity: "پایین",
    nominalCapacity: 10,
    effectiveCapacity: 9,
    productUnit: "مگاوات‌ساعت",
    customProductUnit: "",
    utilizationRate: 0.25,
    wasteRate: 0,
    returnRate: 0,
    cycleTime: 1,
    cycleTimeUnit: "ساعت",
    allowedDowntime: 5,
    downtimeUnit: "درصد",
    seasonalityFactor: 0,
    bottleneckPoint: "ندارد",
    capacityGrowthRate: 0,
    firstYearUtilization: 0.6,
    stableUtilization: 0.9,
    efficiency: 0.95,
    productivityIndicators: [
      {
        id: "productivity-solar-efficiency",
        title: "بازدهی ماژول‌های خورشیدی",
        value: 95,
        unit: "درصد",
        description: "شاخص پایه مطابق IndustryTemplate07!R30 و CapacityProduction09",
      },
    ],
    mainRevenueType: "فروش محصول",
    sideRevenueEnabled: false,
    sideRevenueDescription: "ندارد",
    pricingModel: "قیمت مبتنی بر قرارداد",
    mainCostType: "تعمیر و نگهداری",
    dominantVariableCost: "نگهداری و تعمیرات",
    dominantFixedCost: "هزینه سرمایه",
    systemSuggestedCostStructure: {
      suggestedMainCostType: "انرژی",
      suggestedDominantVariableCost: "تعمیر و نگهداری",
      suggestedDominantFixedCost: "هزینه سرمایه",
      suggestedWorkingCapitalSensitivity: "متوسط",
      confidence: 0.78,
      explanation: "پروژه انرژی خورشیدی سرمایه‌بر است و هزینه ثابت سرمایه و نگهداری سهم غالب دارند.",
    },
    revenueFxShare: 0,
    costFxExposureTable: [
      { id: "fx-cost-materials", costGroup: "مواد اولیه", totalCostShare: 0.1, fxShare: 0.8, fxType: "freeMarket", description: "تجهیزات و قطعات وارداتی" },
      { id: "fx-cost-energy", costGroup: "انرژی", totalCostShare: 0.05, fxShare: 0, fxType: "official", description: "تعرفه داخلی" },
      { id: "fx-cost-labor", costGroup: "نیروی انسانی", totalCostShare: 0.15, fxShare: 0, fxType: "official", description: "هزینه ریالی" },
      { id: "fx-cost-contractor", costGroup: "پیمانکار", totalCostShare: 0.15, fxShare: 0.2, fxType: "freeMarket", description: "بخشی وابسته به تجهیزات" },
      { id: "fx-cost-cloud", costGroup: "زیرساخت / Cloud / Server", totalCostShare: 0.05, fxShare: 0.5, fxType: "freeMarket", description: "زیرساخت پایش" },
      { id: "fx-cost-license", costGroup: "لایسنس / API / ابزار خارجی", totalCostShare: 0.05, fxShare: 1, fxType: "freeMarket", description: "ابزار خارجی" },
      { id: "fx-cost-marketing", costGroup: "بازاریابی", totalCostShare: 0.05, fxShare: 0, fxType: "official", description: "هزینه ریالی" },
      { id: "fx-cost-logistics", costGroup: "حمل و لجستیک", totalCostShare: 0.2, fxShare: 0.4, fxType: "remittance", description: "حمل تجهیزات" },
      { id: "fx-cost-other", costGroup: "سایر", totalCostShare: 0.2, fxShare: 0.3, fxType: "manual", manualRate: 500000, description: "قابل تنظیم" },
    ],
    receivablesDays: 60,
    payablesDays: 30,
    workingCapitalSensitivity: "متوسط",
    risks: [
      { id: "risk-supply", title: "تأمین مواد و تجهیزات", level: "متوسط", probability: 3, impact: 4, mitigation: "قرارداد تأمین و موجودی قطعات یدکی", modelEffect: "CAPEX و تأخیر" },
      { id: "risk-fx", title: "ریسک ارزی", level: "بالا", probability: 4, impact: 5, mitigation: "پوشش ارزی و خرید مرحله‌ای", modelEffect: "CAPEX/OPEX" },
      { id: "risk-permit", title: "ریسک مجوز", level: "پایین", probability: 2, impact: 3, mitigation: "پیگیری مجوز وزارت نیرو", modelEffect: "تاریخ بهره‌برداری" },
      { id: "risk-sales", title: "ریسک فروش", level: "پایین", probability: 2, impact: 3, mitigation: "قرارداد خرید تضمینی", modelEffect: "Revenue" },
      { id: "risk-finance", title: "ریسک تأمین مالی", level: "متوسط", probability: 3, impact: 5, mitigation: "تثبیت ساختار وام و آورده", modelEffect: "DSCR" },
      { id: "risk-execution", title: "ریسک اجرایی", level: "پایین", probability: 2, impact: 3, mitigation: "کنترل EPC و برنامه ساخت", modelEffect: "Construction Cash Flow" },
    ],
    supplyRisk: "متوسط",
    importedCostShare: 0.8,
    governmentTariffDependence: 1,
    fxRisk: "بالا",
    permitRisk: "پایین",
    salesRisk: "پایین",
    financingRisk: "متوسط",
    executionRisk: "پایین",
    specialPermitRequired: true,
    specialPermits: "مجوز وزارت نیرو",
    mandatoryStandardRequired: true,
    mandatoryStandards: "استاندارد برق تجدیدپذیر",
    priceSensitivity: "پایین",
    fxSensitivity: "بالا",
    keyProductivityMetric: "بازدهی ماژول‌های خورشیدی",
    notes: "وابستگی بالا به ارز برای تجهیزات",
  },
  market: {
    mainMarket: "برق شبکه سراسری",
    marketSegment: "برق تجدیدپذیر",
    targetCustomer: "شرکت توانیر",
    targetRegion: "ملی",
    salesChannel: "قرارداد خرید تضمینی",
    marketAnalysisUnit: "مگاوات ساعت",
    unit: "مگاوات ساعت",
    totalMarketSize: 300000000,
    serviceableAvailableMarket: 10000000,
    addressableMarket: 10000000,
    targetMarketSize: 21900,
    targetMarket: 21900,
    targetShare: 0.00219,
    targetMarketShare: 0.00219,
    marketGrowthRate: 0.04,
    initialPenetrationRate: 1,
    penetrationRate: 1,
    maxPenetrationRate: 1,
    penetrationCap: 1,
    marketAbsorptionCapacity: 21900,
    demandLimit: 50000,
    hasSupplyConstraint: true,
    supplyConstraintValue: 19715.338125,
    demandBehavior: {
      priceSensitivity: "پایین",
      qualitySensitivity: "پایین",
      deliverySensitivity: "پایین",
      brandSensitivity: "پایین",
      permitSensitivity: "بالا",
      seasonalityEnabled: true,
      seasonalityFactor: 1,
      seasonalityDescription: "الگوی ماهانه مطابق تولید خورشیدی",
      purchasePattern: "قراردادی",
      customerGrowthRate: 0,
      retentionRate: 1,
      conversionRate: 1,
    },
    potentialSalesYear1: 19715.338125,
    potentialSalesYear2: 20701.10503125,
    potentialSalesYear3: 21736.1602828125,
    salesGrowthRate: 0.05,
    marketAchievementFactor: 1,
    salesCeiling: 50000,
    achievableSalesOverrideEnabled: false,
    achievableSalesOverride: null,
    achievableSales: 19715.338125,
    unitSalesPrice: 1200000,
    potentialRevenue: 23658405750,
    baseSalesPrice: 1200000,
    priceGrowthRate: 0.05,
    domesticShare: 1,
    exportShare: 0,
    customerConcentrationRisk: "بالا",
    marketRiskScore: 45,
    finalNotes: "قرارداد بلندمدت خرید برق تضمینی",
  },
  capacity: {
    unit: "مگاوات‌ساعت",
    nominalCapacity: 10,
    productionLines: 1,
    workingDaysPerYear: 365,
    shiftsPerDay: 1,
    effectiveHoursPerShift: 7,
    plannedDowntimeRate: 0.05,
    unplannedDowntimeRate: 0.05,
    firstYearUtilizationRate: 0.6,
    secondYearUtilizationRate: 0.8,
    stableYearUtilizationRate: 0.9,
    utilizationYear1: 0.6,
    utilizationYear2: 0.8,
    utilizationStable: 0.9,
    productionEfficiency: 0.95,
    wasteRate: 0,
    yieldRate: 0.95,
    bottleneckHourlyCapacity: 10,
    bottleneckCapacityPerHour: 10,
    energyConstraintType: "ندارد",
    energyAvailableQuantity: 0,
    energyLimit: 0,
    energyConsumptionPerUnit: 0,
    energyPerUnit: 0,
    hasRawMaterialConstraint: false,
    constrainedRawMaterialName: "",
    rawMaterialAvailableQuantity: 0,
    rawMaterialQuantityUnit: "کیلوگرم",
    rawMaterialAvailabilityPeriod: "سالانه",
    rawMaterialToProductConversionFactor: 0,
    materialLimit: 0,
    trialProductionStartDate: "2027-06-01",
    rampUpDurationMonths: 6,
    rampUpMonths: 6,
    monthlyRampUpCapacityPercentages: [
      { month: 1, capacityPercent: 0.25 },
      { month: 2, capacityPercent: 0.35 },
      { month: 3, capacityPercent: 0.45 },
      { month: 4, capacityPercent: 0.5 },
      { month: 5, capacityPercent: 0.55 },
      { month: 6, capacityPercent: 0.6 },
      { month: 7, capacityPercent: 0.6 },
      { month: 8, capacityPercent: 0.6 },
      { month: 9, capacityPercent: 0.6 },
      { month: 10, capacityPercent: 0.6 },
      { month: 11, capacityPercent: 0.6 },
      { month: 12, capacityPercent: 0.6 },
    ],
    seasonalityMode: "یکنواخت",
    monthlyProductionDistribution: [
      { month: 1, label: "فروردین", share: 1 / 12 },
      { month: 2, label: "اردیبهشت", share: 1 / 12 },
      { month: 3, label: "خرداد", share: 1 / 12 },
      { month: 4, label: "تیر", share: 1 / 12 },
      { month: 5, label: "مرداد", share: 1 / 12 },
      { month: 6, label: "شهریور", share: 1 / 12 },
      { month: 7, label: "مهر", share: 1 / 12 },
      { month: 8, label: "آبان", share: 1 / 12 },
      { month: 9, label: "آذر", share: 1 / 12 },
      { month: 10, label: "دی", share: 1 / 12 },
      { month: 11, label: "بهمن", share: 1 / 12 },
      { month: 12, label: "اسفند", share: 1 / 12 },
    ],
  },
  directCosts: {
    method: "unitCost",
    cogsPercent: 0.005,
    mainRawMaterialName: "ماده اولیه اصلی",
    isMainRawMaterialFx: false,
    mainRawMaterialFxShare: 0,
    mainRawMaterialRialPrice: 0,
    mainRawMaterialFxPrice: 0,
    mainRawMaterialFxRateType: "freeMarket",
    rawMaterialFxUnitCost: 0,
    rawMaterialRialUnitCost: 0,
    rawMaterialFxShare: 0,
    secondaryMaterialsCost: 0,
    secondaryMaterialsUnitCost: 0,
    packagingUnitCost: 0,
    directEnergyCost: 0,
    energyUnitCost: 0,
    directLaborCost: 5000,
    directLaborUnitCost: 5000,
    avoidableWasteCost: 0,
    avoidableWasteRate: 0,
    directTransportCost: 0,
    logisticsUnitCost: 0,
    salesCommissionCost: 0,
    salesCommissionRate: 0,
    importDutiesAndClearanceCost: 0,
    customsUnitCost: 0,
    otherDirectProductionCosts: 0,
    otherUnitCost: 0,
    rialRawMaterialGrowthRate: 0,
    rawMaterialRialGrowth: 0,
    fxRawMaterialGrowthRate: 0,
    rawMaterialFxGrowth: 0,
    directLaborGrowthFactor: 0.15,
    wageGrowth: 0.15,
    energyTariffGrowthRate: 0.1,
    energyGrowth: 0.1,
    economiesOfScaleSavingPercent: 0,
    scaleSavingRate: 0,
    items: [
      { id: "dc-secondary", name: "مواد ثانویه", rialUnitCost: 0, fxUnitCost: 0, costType: "ریالی", fxShare: 0, fxRateType: "freeMarket", behavior: "متغیر", description: "COGS-DirectCost10!Q19" },
      { id: "dc-packaging", name: "بسته‌بندی", rialUnitCost: 0, fxUnitCost: 0, costType: "ریالی", fxShare: 0, fxRateType: "freeMarket", behavior: "متغیر", description: "COGS-DirectCost10!Q20" },
      { id: "dc-energy", name: "انرژی مستقیم", rialUnitCost: 0, fxUnitCost: 0, costType: "ریالی", fxShare: 0, fxRateType: "official", behavior: "متغیر", description: "COGS-DirectCost10!Q21" },
      { id: "dc-labor", name: "دستمزد مستقیم", rialUnitCost: 5000, fxUnitCost: 0, costType: "ریالی", fxShare: 0, fxRateType: "official", behavior: "متغیر", description: "COGS-DirectCost10!Q22" },
      { id: "dc-transport", name: "حمل مستقیم", rialUnitCost: 0, fxUnitCost: 0, costType: "ریالی", fxShare: 0, fxRateType: "freeMarket", behavior: "متغیر", description: "COGS-DirectCost10!Q24" },
      { id: "dc-customs", name: "حقوق و ترخیص", rialUnitCost: 0, fxUnitCost: 0, costType: "ترکیبی", fxShare: 0, fxRateType: "freeMarket", behavior: "متغیر", description: "COGS-DirectCost10!Q26" },
      { id: "dc-other", name: "سایر هزینه مستقیم", rialUnitCost: 0, fxUnitCost: 0, costType: "ریالی", fxShare: 0, fxRateType: "freeMarket", behavior: "متغیر", description: "COGS-DirectCost10!Q27" },
    ],
  },
  opex: {
    items: [
      { id: "op-salaries", name: "حقوق اداری", group: "منابع انسانی", baseYearAmount: 1000000000, cashOrNonCash: "نقدی", isFx: false, fxShare: 0, fxRateType: "official", growthRate: 0.1, costDriver: "وابسته به تعداد پرسنل", overheadAllocationPercent: 0, notes: "Opex-Indirect11!Q20" },
      { id: "op-insurance", name: "بیمه سهم کارفرما", group: "منابع انسانی", baseYearAmount: 200000000, cashOrNonCash: "نقدی", isFx: false, fxShare: 0, fxRateType: "official", growthRate: 0.1, costDriver: "وابسته به تعداد پرسنل", overheadAllocationPercent: 0, notes: "۲۰٪ حقوق؛ Opex-Indirect11!Q21" },
      { id: "op-bonuses", name: "پاداش و مزایا", group: "منابع انسانی", baseYearAmount: 500000000, cashOrNonCash: "نقدی", isFx: false, fxShare: 0, fxRateType: "official", growthRate: 0.1, costDriver: "وابسته به تعداد پرسنل", overheadAllocationPercent: 0, notes: "Opex-Indirect11!Q22" },
      { id: "op-rent", name: "اجاره", group: "اداری و عمومی", baseYearAmount: 200000000, cashOrNonCash: "نقدی", isFx: false, fxShare: 0, fxRateType: "official", growthRate: 0.1, costDriver: "وابسته به قرارداد", overheadAllocationPercent: 0, notes: "Opex-Indirect11!Q23" },
      { id: "op-maintenance", name: "نگهداری ساختمان", group: "اداری و عمومی", baseYearAmount: 100000000, cashOrNonCash: "نقدی", isFx: false, fxShare: 0, fxRateType: "official", growthRate: 0.1, costDriver: "وابسته به تورم عمومی", overheadAllocationPercent: 0, notes: "Opex-Indirect11!Q24" },
      { id: "op-utilities", name: "آب، برق و خدمات", group: "اداری و عمومی", baseYearAmount: 50000000, cashOrNonCash: "نقدی", isFx: false, fxShare: 0, fxRateType: "official", growthRate: 0.1, costDriver: "وابسته به تورم عمومی", overheadAllocationPercent: 0, notes: "Opex-Indirect11!Q25" },
      { id: "op-it", name: "فناوری اطلاعات", group: "فناوری و زیرساخت", baseYearAmount: 50000000, cashOrNonCash: "نقدی", isFx: true, fxShare: 0.7, fxRateType: "freeMarket", growthRate: 0.1, costDriver: "وابسته به نرخ ارز", overheadAllocationPercent: 0, notes: "Opex-Indirect11!Q26" },
      { id: "op-marketing", name: "بازاریابی", group: "فروش و بازاریابی", baseYearAmount: 0, cashOrNonCash: "نقدی", isFx: false, fxShare: 0, fxRateType: "official", growthRate: 0.1, costDriver: "وابسته به درآمد", overheadAllocationPercent: 0, notes: "Opex-Indirect11!Q27" },
      { id: "op-selling", name: "هزینه فروش", group: "فروش و بازاریابی", baseYearAmount: 0, cashOrNonCash: "نقدی", isFx: false, fxShare: 0, fxRateType: "official", growthRate: 0.1, costDriver: "وابسته به درآمد", overheadAllocationPercent: 0, notes: "Opex-Indirect11!Q28" },
      { id: "op-travel", name: "ماموریت و سفر", group: "اداری و عمومی", baseYearAmount: 100000000, cashOrNonCash: "نقدی", isFx: false, fxShare: 0, fxRateType: "official", growthRate: 0.1, costDriver: "وابسته به تورم عمومی", overheadAllocationPercent: 0, notes: "Opex-Indirect11!Q29" },
      { id: "op-logistics", name: "لجستیک غیرمستقیم", group: "سربار تولید", baseYearAmount: 0, cashOrNonCash: "نقدی", isFx: false, fxShare: 0, fxRateType: "official", growthRate: 0.1, costDriver: "وابسته به تولید", overheadAllocationPercent: 1, notes: "Opex-Indirect11!Q30" },
      { id: "op-legal", name: "حقوقی و حسابرسی", group: "اداری و عمومی", baseYearAmount: 50000000, cashOrNonCash: "نقدی", isFx: false, fxShare: 0, fxRateType: "official", growthRate: 0.1, costDriver: "وابسته به قرارداد", overheadAllocationPercent: 0, notes: "Opex-Indirect11!Q31" },
      { id: "op-banking", name: "کارمزد بانکی", group: "مالی و بانکی", baseYearAmount: 10000000, cashOrNonCash: "نقدی", isFx: false, fxShare: 0, fxRateType: "official", growthRate: 0.1, costDriver: "وابسته به درآمد", overheadAllocationPercent: 0, notes: "Opex-Indirect11!Q32" },
      { id: "op-general-insurance", name: "بیمه عمومی", group: "اداری و عمومی", baseYearAmount: 20000000, cashOrNonCash: "نقدی", isFx: false, fxShare: 0, fxRateType: "official", growthRate: 0.1, costDriver: "وابسته به قرارداد", overheadAllocationPercent: 0, notes: "Opex-Indirect11!Q33" },
      { id: "op-training", name: "آموزش", group: "منابع انسانی", baseYearAmount: 30000000, cashOrNonCash: "نقدی", isFx: false, fxShare: 0, fxRateType: "official", growthRate: 0.1, costDriver: "وابسته به تعداد پرسنل", overheadAllocationPercent: 0, notes: "Opex-Indirect11!Q34" },
      { id: "op-hospitality", name: "پذیرایی", group: "اداری و عمومی", baseYearAmount: 10000000, cashOrNonCash: "نقدی", isFx: false, fxShare: 0, fxRateType: "official", growthRate: 0.1, costDriver: "وابسته به تورم عمومی", overheadAllocationPercent: 0, notes: "Opex-Indirect11!Q35" },
      { id: "op-depreciation", name: "استهلاک غیرتولیدی", group: "غیرنقدی", baseYearAmount: 0, cashOrNonCash: "غیرنقدی", isFx: false, fxShare: 0, fxRateType: "official", growthRate: 0, costDriver: "ثابت", overheadAllocationPercent: 0, notes: "Opex-Indirect11!Q36" },
      { id: "op-taxes", name: "سایر مالیات‌ها", group: "اداری و عمومی", baseYearAmount: 0, cashOrNonCash: "نقدی", isFx: false, fxShare: 0, fxRateType: "official", growthRate: 0.1, costDriver: "وابسته به درآمد", overheadAllocationPercent: 0, notes: "Opex-Indirect11!Q37" },
      { id: "op-other", name: "سایر اداری و عمومی", group: "سایر", baseYearAmount: 0, cashOrNonCash: "نقدی", isFx: false, fxShare: 0, fxRateType: "official", growthRate: 0.1, costDriver: "دستی", overheadAllocationPercent: 0, notes: "Opex-Indirect11!Q38" },
    ],
    sharedCostAllocationPercent: 0,
    allocationToProductionRate: 0,
    salaries: 1000000000,
    employerInsuranceRate: 0.2,
    bonuses: 500000000,
    rent: 200000000,
    buildingMaintenance: 100000000,
    utilities: 50000000,
    it: 50000000,
    marketing: 0,
    selling: 0,
    travel: 100000000,
    logistics: 0,
    legalAudit: 50000000,
    bankingFees: 10000000,
    insurance: 20000000,
    training: 30000000,
    hospitality: 10000000,
    nonProductionDepreciation: 0,
    otherTaxes: 0,
    otherAdmin: 0,
    growthRate: 0.1,
    scenarioAdjustmentRate: 0,
    fxShare: 0.7,
  },
  capex: {
    items: [
      {
        id: "capex-solar-modules",
        code: "CAP-01",
        name: "ماژول‌های خورشیدی و اینورتر",
        assetClass: "ماشین‌آلات و تجهیزات",
        itemType: "خرید",
        depreciable: true,
        unit: "مگاوات",
        description: "ماژول‌ها و اینورترهای نیروگاه",
        source: "استعلام بازار",
        quantity: 10,
        rialUnitPrice: 25000000000,
        fxUnitPrice: 0,
        rialPriceShare: 1,
        fxPriceShare: 0,
        fxRateType: "freeMarket",
        unitPrice: 25000000000,
        currency: "ریال",
        fxRate: 1,
        expectedInflationIncreasePercent: 0.05,
        priceIncreaseRate: 0.05,
        startDate: "2026-09-01",
        endDate: "2027-03-01",
        startYear: 2026,
        endYear: 2027,
        purchaseMonths: 6,
        installationMonths: 6,
        operationPeriodMonths: 240,
        constructionPhase: "ساخت و نصب",
        delayEnabled: false,
        prepaymentRate: 0.5,
        deliveryPaymentRate: 0.3,
        postInstallPaymentRate: 0.2,
        annualDelayEscalationRate: 0.1,
        delayMonths: 0,
        monthlyDelayCost: 100000000,
        fxRisk: "بالا",
        supplyDelayRisk: "متوسط",
        clearanceRisk: "پایین",
        priceIncreaseRisk: "متوسط",
        permitRisk: "پایین",
        contingencyRate: 0.05,
        installationCost: 200000000,
        transportInsuranceCost: 100000000,
        trainingCost: 50000000,
        preOperationCost: 100000000,
        indirectProjectCost: 50000000,
        permitCost: 0,
        permitCostRate: 0.02,
        usefulLifeYears: 20,
        salvageValue: 0,
        salvageValueRate: 0.1,
        depreciationMethod: "خطی",
        depreciationStartDate: "2027-06-01",
        depreciationStartYear: 2027,
        taxEligible: true,
        accountingEligible: true,
        accountingDepreciable: true,
        accountingUsefulLifeYears: 20,
        accountingSalvageValue: 0,
        accountingSalvageValueRate: 0.1,
        accountingDepreciationMethod: "خطی",
        accountingDepreciationStartDate: "2027-06-01",
        accountingDepreciationStartYear: 2027,
        taxDepreciable: true,
        taxUsefulLifeYears: 10,
        taxSalvageValue: 0,
        taxSalvageValueRate: 0,
        taxDepreciationMethod: "خطی",
        taxDepreciationStartDate: "2027-06-01",
        taxDepreciationStartYear: 2027,
      },
    ],
    annualSchedule: [],
    summary: {
      totalFixedInvestment: 0,
      totalFxInvestment: 0,
      totalRialInvestment: 0,
      totalDelayCost: 0,
      totalPreOperationCost: 0,
      totalContingencyCost: 0,
      importedAssetShare: 0,
      domesticAssetShare: 0,
      totalAnnualDepreciation: 0,
      incompleteItemCount: 0,
      highRiskItemCount: 0,
      largestItemName: "",
      largestItemShare: 0,
    },
  },
  workingCapital: {
    rawMaterialDays: 0,
    inventoryDays: 15,
    receivableDays: 60,
    payableDays: 30,
    supplierPrepaymentDays: 30,
    minimumCashDays: 30,
    accruedExpenseDays: 15,
    otherCurrentLiabilitiesPercentOfRevenue: 0,
    releaseInFinalYear: true,
  },
  financing: {
    equity: 120000000000,
    shortTermDebt: 0,
    longTermDebt: 2100000000000,
    gracePeriodYears: 2,
    interestRate: 0.2,
    feeRate: 0.01,
    repaymentMethod: "قسط ثابت",
    repaymentYears: 10,
    collateral: "زمین و تجهیزات نیروگاه",
    targetDebtToEquity: 0.7,
    dividendPolicy: "عدم تقسیم سود تا پایان دوره بازپرداخت",
    lenderCovenants: "پرداخت به‌موقع و نرخ ثابت",
    loanType: "وام بانکی ساده",
    interestDuringGraceBehavior: "پرداخت بهره در تنفس",
    drawdown: {
      0: 1680000000000,
      1: 420000000000,
      2: 0,
    },
    preferredShareAmount: 0,
    preferredDividendRate: 0,
    ordinaryDividendPayout: 0,
    targetDscr: 1.25,
    drawdownModel: "manual",
    selectedDrawdownYears: [0, 1, 2],
    instruments: [
      {
        id: "facility-main-bank",
        title: "وام بانکی ساده",
        type: "simpleBankLoan",
        active: true,
        amount: 2100000000000,
        annualRate: 0.2,
        feeRate: 0.01,
        graceEnabled: true,
        graceMonths: 24,
        graceCostBehavior: "paidDuringGrace",
        repaymentTermMonths: 120,
        paymentFrequency: "annual",
        repaymentMethod: "fixedInstallment",
        balloonPercent: 0,
        stepRate: 0.05,
        upfrontPaymentPercent: 0,
        blockedDepositPercent: 0,
        blockedDepositOpportunityRate: 0,
        guaranteeFeeRate: 0,
        collateralRequired: true,
        collateralItems: ["زمین پروژه", "ماشین‌آلات و تجهیزات"],
        collateralText: "زمین و تجهیزات نیروگاه",
        guaranteeRequired: false,
        guaranteeTypes: [],
        dividendPolicy: "عدم تقسیم سود تا پایان دوره بازپرداخت",
        covenantsText: "پرداخت به‌موقع و نرخ ثابت",
      },
      {
        id: "facility-qard",
        title: "قرض‌الحسنه",
        type: "qardAlHasan",
        active: false,
        amount: 0,
        annualRate: 0.04,
        feeRate: 0,
        graceEnabled: false,
        graceMonths: 0,
        graceCostBehavior: "paidDuringGrace",
        repaymentTermMonths: 36,
        paymentFrequency: "monthly",
        repaymentMethod: "equalPrincipal",
        balloonPercent: 0,
        stepRate: 0,
        upfrontPaymentPercent: 0,
        blockedDepositPercent: 0,
        blockedDepositOpportunityRate: 0,
        guaranteeFeeRate: 0,
        collateralRequired: false,
        collateralItems: [],
        collateralText: "",
        guaranteeRequired: true,
        guaranteeTypes: ["چک / سفته ضمانتی"],
        dividendPolicy: "عدم تقسیم سود تا پایان دوره بازپرداخت",
        covenantsText: "کارمزد قرض‌الحسنه به‌عنوان بهره متعارف شناسایی نمی‌شود.",
      },
      {
        id: "facility-murabaha",
        title: "مرابحه",
        type: "murabaha",
        active: false,
        amount: 0,
        annualRate: 0.18,
        feeRate: 0,
        graceEnabled: false,
        graceMonths: 0,
        graceCostBehavior: "paidDuringGrace",
        repaymentTermMonths: 60,
        paymentFrequency: "quarterly",
        repaymentMethod: "equalMurabahaInstallments",
        balloonPercent: 0,
        stepRate: 0.05,
        upfrontPaymentPercent: 0,
        blockedDepositPercent: 0,
        blockedDepositOpportunityRate: 0,
        guaranteeFeeRate: 0,
        collateralRequired: true,
        collateralItems: ["قرارداد فروش / مطالبات"],
        collateralText: "",
        guaranteeRequired: false,
        guaranteeTypes: [],
        dividendPolicy: "تقسیم فقط پس از رعایت حداقل DSCR",
        covenantsText: "مصرف تسهیلات باید قابل ردیابی به خرید کالا/خدمت باشد.",
      },
      {
        id: "facility-installment-sale",
        title: "فروش اقساطی",
        type: "installmentSale",
        active: false,
        amount: 0,
        annualRate: 0.18,
        feeRate: 0,
        graceEnabled: false,
        graceMonths: 0,
        graceCostBehavior: "paidDuringGrace",
        repaymentTermMonths: 72,
        paymentFrequency: "quarterly",
        repaymentMethod: "fixedInstallment",
        balloonPercent: 0.1,
        stepRate: 0.05,
        upfrontPaymentPercent: 0.1,
        blockedDepositPercent: 0,
        blockedDepositOpportunityRate: 0,
        guaranteeFeeRate: 0,
        collateralRequired: true,
        collateralItems: ["ماشین‌آلات و تجهیزات"],
        collateralText: "",
        guaranteeRequired: false,
        guaranteeTypes: [],
        dividendPolicy: "تقسیم مازاد نقدینگی پس از خدمت بدهی",
        covenantsText: "دارایی موضوع فروش اقساطی باید در مدل CAPEX قابل شناسایی باشد.",
      },
      {
        id: "facility-juala",
        title: "جعاله",
        type: "juala",
        active: false,
        amount: 0,
        annualRate: 0.17,
        feeRate: 0,
        graceEnabled: false,
        graceMonths: 0,
        graceCostBehavior: "paidDuringGrace",
        repaymentTermMonths: 48,
        paymentFrequency: "quarterly",
        repaymentMethod: "milestoneBased",
        balloonPercent: 0,
        stepRate: 0.05,
        upfrontPaymentPercent: 0.2,
        blockedDepositPercent: 0,
        blockedDepositOpportunityRate: 0,
        guaranteeFeeRate: 0,
        collateralRequired: true,
        collateralItems: ["صورت‌وضعیت پیمانکاری"],
        collateralText: "",
        guaranteeRequired: true,
        guaranteeTypes: ["ضمانت‌نامه حسن انجام تعهدات"],
        dividendPolicy: "تقسیم فقط پس از رعایت حداقل DSCR",
        covenantsText: "پرداخت‌ها بر اساس پیشرفت کار و صورت‌وضعیت قابل کنترل انجام شود.",
      },
    ],
    drawdownRows: [
      { year: 0, instrumentId: "facility-main-bank", amount: 1680000000000, percentOfInstrument: 0.8 },
      { year: 1, instrumentId: "facility-main-bank", amount: 420000000000, percentOfInstrument: 0.2 },
      { year: 2, instrumentId: "facility-main-bank", amount: 0, percentOfInstrument: 0 },
    ],
  },
  construction: {
    bufferMonths: 3,
    monthlyDevelopmentPayroll: 120000000,
    monthlyContractorCost: 70000000,
    monthlyInfrastructureCost: 95000000,
    monthlyTestingCost: 60000000,
    deploymentTrainingCost: 150000000,
    minimumCashReserve: 345000000,
    monthlyAdjustmentEnabled: true,
    equityTimingMethod: "محافظه‌کارانه",
    debtTimingMethod: "محافظه‌کارانه",
    creditLineEnabled: true,
    creditLineRate: 0.2,
    delayScenarioEnabled: false,
    analysisMonths: 12,
    monthlyInflationRate: 0.0153,
    monthlyFxGrowthRate: 0.014,
    delayMonthlyCost: 0,
    creditLineCap: 0,
    creditLineFeeRate: 0,
    delayAdjustmentRate: 0,
    allowedDelayMonths: 0,
    actualDelayMonths: 0,
    capexMilestones: [
      { id: "prepayment", title: "پیش‌پرداخت", percent: 0.2, paymentMonth: 1, active: true },
      { id: "delivery", title: "تحویل", percent: 0.5, paymentMonth: 5, active: true },
      { id: "postInstallation", title: "پس از نصب/استقرار", percent: 0.3, paymentMonth: 9, active: true },
    ],
    costItems: [
      { id: "development-team", title: "تیم توسعه", baseAmount: 120000000, active: true, isMonthly: true, selectedMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9], inflationIndexed: true, fxIndexed: false, fxShare: 0, rialShare: 1, distributionMode: "repeatMonthly", description: "Backend، Frontend، Data، DevOps، PM", isCustom: false },
      { id: "contractor", title: "پیمانکار", baseAmount: 70000000, active: true, isMonthly: true, selectedMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9], inflationIndexed: true, fxIndexed: true, fxShare: 0.15, rialShare: 0.85, distributionMode: "repeatMonthly", description: "پیمانکار توسعه و پیاده‌سازی", isCustom: false },
      { id: "technical-consultant", title: "مشاور فنی", baseAmount: 0, active: true, isMonthly: true, selectedMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9], inflationIndexed: true, fxIndexed: false, fxShare: 0, rialShare: 1, distributionMode: "repeatMonthly", description: "مشاور فنی و کنترل پروژه", isCustom: false },
      { id: "server", title: "سرور", baseAmount: 42750000, active: true, isMonthly: true, selectedMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9], inflationIndexed: true, fxIndexed: true, fxShare: 0.6, rialShare: 0.4, distributionMode: "repeatMonthly", description: "Cloud و زیرساخت", isCustom: false },
      { id: "special-license", title: "لایسنس خاص", baseAmount: 23750000, active: true, isMonthly: true, selectedMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9], inflationIndexed: true, fxIndexed: true, fxShare: 0.8, rialShare: 0.2, distributionMode: "repeatMonthly", description: "لایسنس نرم‌افزار", isCustom: false },
      { id: "api", title: "API", baseAmount: 28500000, active: true, isMonthly: true, selectedMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9], inflationIndexed: true, fxIndexed: true, fxShare: 0.5, rialShare: 0.5, distributionMode: "repeatMonthly", description: "API و سرویس‌های بیرونی", isCustom: false },
      { id: "test", title: "تست", baseAmount: 21000000, active: true, isMonthly: true, selectedMonths: [8, 9], inflationIndexed: true, fxIndexed: false, fxShare: 0, rialShare: 1, distributionMode: "repeatMonthly", description: "تست فنی و عملکردی", isCustom: false },
      { id: "security", title: "امنیت", baseAmount: 21000000, active: true, isMonthly: true, selectedMonths: [8, 9], inflationIndexed: true, fxIndexed: false, fxShare: 0, rialShare: 1, distributionMode: "repeatMonthly", description: "امنیت و آزمون نفوذ", isCustom: false },
      { id: "qa", title: "QA", baseAmount: 18000000, active: true, isMonthly: true, selectedMonths: [8, 9], inflationIndexed: true, fxIndexed: false, fxShare: 0, rialShare: 1, distributionMode: "repeatMonthly", description: "کنترل کیفیت مدل و محصول", isCustom: false },
      { id: "deployment", title: "هزینه استقرار", baseAmount: 67500000, active: true, isMonthly: false, selectedMonths: [9], inflationIndexed: true, fxIndexed: false, fxShare: 0, rialShare: 1, distributionMode: "equalSplitAcrossSelectedMonths", description: "استقرار و قبولی", isCustom: false },
      { id: "training", title: "هزینه آموزش", baseAmount: 52500000, active: true, isMonthly: false, selectedMonths: [9], inflationIndexed: true, fxIndexed: false, fxShare: 0, rialShare: 1, distributionMode: "equalSplitAcrossSelectedMonths", description: "آموزش تیم بهره‌برداری", isCustom: false },
      { id: "documentation", title: "هزینه مستندسازی", baseAmount: 30000000, active: true, isMonthly: false, selectedMonths: [9], inflationIndexed: true, fxIndexed: false, fxShare: 0, rialShare: 1, distributionMode: "equalSplitAcrossSelectedMonths", description: "مستندسازی و تحویل دانش", isCustom: false },
    ],
  },
  tax: {
    assetClass: "تجهیزات",
    accountingUsefulLifeYears: 20,
    taxUsefulLifeYears: 10,
    accountingMethod: "خطی",
    taxMethod: "خطی",
    exemptionType: "معافیت مناطق کمتر توسعه یافته",
    exemptionRate: 0.2,
    exemptionYears: 5,
    exemptionStartYear: 1,
    preferredTaxRate: 0,
    investmentTaxCredit: 0.1,
    incentiveType: "منطقه کمتر توسعه‌یافته",
    normalTaxRateOverride: null,
    approvedKnowledgeRevenueShare: 0.7,
    knowledgeBasedExemptionYears: 15,
    knowledgeBasedStartYear: 1,
    freeZoneInsideActivityShare: 1,
    freeZonePermitDate: "2027-06-01",
    freeZonePermitValid: false,
    freeZoneExemptionYears: 20,
    lessDevelopedEligibleIncomeShare: 0.2,
    lessDevelopedZeroRateYears: 5,
    lessDevelopedStartYear: 1,
    lessDevelopedActivityType: "تولیدی / انرژی",
    preferentialTaxRate: 0.1,
    preferentialYears: 5,
    preferentialIncomeShare: 1,
    taxCreditAmount: 0,
    taxCreditPercentOfCapex: 0.1,
    annualTaxCreditCap: 0,
    taxCreditCarryForward: true,
    percentExemptionRate: 0.2,
    percentExemptionYears: 5,
    percentExemptionIncomeShare: 1,
    customEligibleIncomeShare: 1,
    customEffectiveTaxRate: 0.25,
    customIncentiveYears: 0,
    customTaxCreditAmount: 0,
    isKnowledgeBased: false,
    isFreeZone: false,
    isLessDevelopedRegion: true,
    isIndustrialTown: false,
  },
  economic: {
    economicDiscountRate: 0.08,
    standardConversionFactor: 0.9,
    unskilledLaborShadowFactor: 0.85,
    skilledLaborShadowFactor: 0.9,
    shadowExchangeRateFactor: 1.1,
    energyShadowFactor: 1.2,
    waterShadowFactor: 0.95,
    capitalServiceChargeRate: 0.15,
    directEmploymentBenefit: 50,
    indirectEmploymentBenefit: 20,
    pollutionReductionBenefit: 10,
    environmentalCost: -5,
    infrastructurePressureCost: -3,
    technologyTransferBenefit: 15,
    importSubstitutionBenefit: 25,
    regionalDevelopmentBenefit: 10,
  },
  sensitivity: {
    selectedMetric: "NPV",
    variable1: "فروش",
    variable2: "هزینه",
    shockLow: -0.1,
    shockHigh: 0.1,
    steps: 5,
    variables: [
      {
        id: "sensitivity-sales-price",
        parameter: "قیمت فروش",
        label: "قیمت فروش",
        low: -0.15,
        high: 0.15,
        steps: 7,
        changeType: "percent",
      },
      {
        id: "sensitivity-capex",
        parameter: "CAPEX",
        label: "هزینه سرمایه‌گذاری",
        low: -0.1,
        high: 0.2,
        steps: 7,
        changeType: "percent",
      },
      {
        id: "sensitivity-fx",
        parameter: "نرخ ارز",
        label: "نرخ ارز",
        low: -0.1,
        high: 0.25,
        steps: 7,
        changeType: "percent",
      },
    ],
  },
  monteCarlo: {
    enabled: false,
    iterations: 1000,
    seed: 123,
    liquidityThreshold: 0,
    npvThreshold: 0,
    variables: [
      { id: "mc-sales-price", name: "شوک قیمت فروش", label: "قیمت فروش", sourceModule: "Revenue / Market Demand", sourcePath: "assumptions.market.baseSalesPrice", unitType: "unitPrice", low: -0.1, mid: 0, high: 0.1, distribution: { type: "pert", min: -0.1, mode: 0, max: 0.1 }, shockMode: "percent", enabled: true, active: true, description: "اثر روی درآمد فروش", exposureLogic: "قیمت فروش پایه و قیمت واحد درآمد را به صورت درصدی تغییر می‌دهد." },
      { id: "mc-sales-volume", name: "شوک حجم فروش", label: "حجم فروش", sourceModule: "Market Demand / Capacity Production", sourcePath: "outputs.revenue.rows[1].salesVolume", unitType: "volume", low: -0.15, mid: 0, high: 0.1, distribution: { type: "triangular", min: -0.15, mode: 0, max: 0.1 }, shockMode: "percent", enabled: true, active: true, description: "اثر روی درآمد فروش", exposureLogic: "راننده‌های بازار و ظرفیت را هم‌زمان مقیاس می‌کند." },
      { id: "mc-fx-rate", name: "شوک نرخ ارز", label: "نرخ ارز", sourceModule: "Macro / FX-linked costs", sourcePath: "assumptions.macro.fxRates", unitType: "fxRate", low: -0.05, mid: 0.08, high: 0.25, distribution: { type: "pert", min: -0.05, mode: 0.08, max: 0.25 }, shockMode: "percent", enabled: true, active: true, description: "اثر روی هزینه‌های وابسته به ارز", exposureLogic: "فقط نرخ‌های ارز و نرخ‌های دستی اقلام ارزی را تغییر می‌دهد." },
      { id: "mc-inflation", name: "شوک تورم", label: "تورم", sourceModule: "Macro", sourcePath: "assumptions.macro.inflationGeneralAnnual", unitType: "percentage", low: -0.03, mid: 0.02, high: 0.08, distribution: { type: "pert", min: -0.03, mode: 0.02, max: 0.08 }, shockMode: "rateDelta", enabled: true, active: true, description: "اثر روی OPEX", exposureLogic: "تورم عمومی و نرخ تورم مدل را با تغییر واحد درصدی جابه‌جا می‌کند." },
      { id: "mc-capex", name: "شوک CAPEX", label: "CAPEX", sourceModule: "CAPEX", sourcePath: "outputs.capex.totalCapex", unitType: "totalMoney", low: -0.05, mid: 0.08, high: 0.25, distribution: { type: "pert", min: -0.05, mode: 0.08, max: 0.25 }, shockMode: "percent", enabled: true, active: true, description: "افزایش سرمایه‌گذاری اولیه", exposureLogic: "قیمت‌ها و هزینه‌های اقلام سرمایه‌ای را مقیاس می‌کند." },
      { id: "mc-debt-interest", name: "شوک بهره وام", label: "نرخ بهره بدهی", sourceModule: "Financing", sourcePath: "assumptions.financing.instruments[].annualRate", unitType: "percentage", low: -0.02, mid: 0.01, high: 0.04, distribution: { type: "discrete", values: [{ value: -0.02, probability: 0.2 }, { value: 0.01, probability: 0.5 }, { value: 0.04, probability: 0.3 }] }, shockMode: "rateDelta", enabled: true, active: true, description: "افزایش نرخ بهره بدهی", exposureLogic: "نرخ ابزارهای بدهی فعال و برنامه DSCR را تغییر می‌دهد." },
      { id: "mc-delay", name: "شوک تاخیر اجرا", label: "تاخیر اجرا", sourceModule: "Construction Cashflow / CAPEX", sourcePath: "assumptions.construction.actualDelayMonths", unitType: "months", low: 0, mid: 4, high: 12, distribution: { type: "discrete", values: [{ value: 0, probability: 0.45 }, { value: 4, probability: 0.35 }, { value: 12, probability: 0.2 }] }, shockMode: "absolute", enabled: true, active: true, description: "ماه", exposureLogic: "تاخیر ساخت و تاخیر اقلام CAPEX را فعال می‌کند." },
      { id: "mc-material-cost", name: "شوک هزینه مواد", label: "هزینه مواد", sourceModule: "Direct Costs / COGS", sourcePath: "outputs.directCosts.rows[1].totalCost", unitType: "totalMoney", low: -0.05, mid: 0.08, high: 0.25, distribution: { type: "pert", min: -0.05, mode: 0.08, max: 0.25 }, shockMode: "percent", enabled: true, active: true, description: "اثر روی COGS", exposureLogic: "مواد و اقلام COGS را مقیاس می‌کند." },
      { id: "mc-labor-cost", name: "شوک دستمزد", label: "دستمزد", sourceModule: "OPEX / Direct Costs", sourcePath: "assumptions.opex.salaries", unitType: "totalMoney", low: 0, mid: 0.12, high: 0.28, distribution: { type: "pert", min: 0, mode: 0.12, max: 0.28 }, shockMode: "percent", enabled: true, active: true, description: "اثر روی OPEX", exposureLogic: "هزینه‌های عملیاتی مرتبط با نیروی انسانی را مقیاس می‌کند." },
      { id: "mc-energy-cost", name: "شوک انرژی", label: "انرژی", sourceModule: "Direct Costs / OPEX", sourcePath: "assumptions.directCosts.directEnergyCost", unitType: "energy", low: 0, mid: 0.1, high: 0.4, distribution: { type: "pert", min: 0, mode: 0.1, max: 0.4 }, shockMode: "percent", enabled: true, active: true, description: "اثر روی OPEX", exposureLogic: "هزینه انرژی و اقلام مستقیم مرتبط را مقیاس می‌کند." },
      { id: "mc-receivable-days", name: "شوک وصول مطالبات", label: "روزهای وصول مطالبات", sourceModule: "Working Capital", sourcePath: "assumptions.workingCapital.receivableDays", unitType: "days", low: 0, mid: 30, high: 60, distribution: { type: "triangular", min: 0, mode: 30, max: 60 }, shockMode: "absolute", enabled: true, active: true, description: "روز اضافه‌شده به دوره وصول", exposureLogic: "روزهای وصول مطالبات را در برنامه سرمایه در گردش تغییر می‌دهد." },
    ],
  },
};

export const seedProject: Project = {
  id: "solar-kerman",
  projectId: "solar-kerman",
  version: 1,
  createdAt: now,
  updatedAt: now,
  setup: {
    projectName: "نیروگاه خورشیدی 10 مگاواتی کرمان",
    projectCode: "IR-FS-2026-001",
    clientName: "شرکت سان‌رایز انرژی",
    preparedBy: "گروه مطالعات پروژه",
    reviewedBy: "تیم کنترل",
    approvedBy: "مدیر پروژه",
    modelPreparedDate: "2026-05-19",
    modelVersion: "1.0",
    fileStatus: "نسخه اولیه",
    projectType: "انرژی",
    legalPersonality: "شرکت با مسئولیت محدود",
    ownershipType: "خصوصی",
    registrationStatus: "ثبت‌شده",
    isKnowledgeBased: false,
    isFreeZone: false,
    isSpecialEconomicZone: false,
    isIndustrialTown: false,
    isLessDevelopedRegion: false,
    mainIndustry: "انرژی",
    subIndustry: "نیروگاه خورشیدی",
    businessModel: "تولید برق و فروش به شبکه",
    projectScale: "متوسط",
    primaryTargetMarket: "داخلی",
    province: "کرمان",
    city: "کرمان",
    baseYear: 2026,
    constructionStartDate: "2026-09-01",
    operationStartDate: "2027-06-01",
    operationStartDateOverrideEnabled: false,
    operationStartDateManual: "2027-06-01",
    constructionDurationMonths: 9,
    analysisHorizonYears: 20,
    fiscalYearEnd: "اسفند",
    calculationBasis: "واقعی",
    baseCurrency: "ریال",
    displayUnit: "billion-rial",
    activeScenarioId: "scenario-base",
    scenarioStatus: "سناریوی پایه",
  },
  name: "نیروگاه خورشیدی 10 مگاواتی کرمان",
  code: "IR-FS-2026-001",
  companyName: "شرکت سان‌رایز انرژی",
  industry: "انرژی",
  subIndustry: "نیروگاه خورشیدی",
  projectType: "انرژی",
  province: "کرمان",
  city: "کرمان",
  legalEntityType: "شرکت با مسئولیت محدود",
  preparedBy: "گروه مطالعات پروژه",
  reviewedBy: "تیم کنترل",
  approvedBy: "مدیر پروژه",
  purpose: "تحلیل اقتصادی و مالی احداث نیروگاه خورشیدی",
  baseYear: 2026,
  constructionStartDate: "2026-09-01",
  operationStartDate: "2027-06-01",
  constructionDurationMonths: 9,
  rampUpMonths: 6,
  modelHorizonYears: 20,
  currency: "ریال",
  displayUnit: "billion-rial",
  activeScenarioId: "scenario-base",
  scenarios: [
    {
      id: "scenario-base",
      projectId: "solar-kerman",
      scenarioId: "scenario-base",
      version: 1,
      createdAt: now,
      updatedAt: now,
      name: "پایه",
      type: "base",
      code: "S01",
      priority: 1,
      isActive: true,
      isLocked: false,
      isDefault: true,
      status: "active",
      description: "سناریوی مرجع مدل مطابق ورودی‌های edition19_4June.xlsx",
      adjustments: defaultScenarioAdjustments("base"),
      assumptions: cloneAssumptions(baseAssumptions),
    },
    {
      id: "scenario-optimistic",
      projectId: "solar-kerman",
      scenarioId: "scenario-optimistic",
      version: 1,
      createdAt: now,
      updatedAt: now,
      name: "خوش‌بینانه",
      type: "optimistic",
      code: "S02",
      priority: 2,
      isActive: false,
      isLocked: false,
      isDefault: true,
      status: "active",
      description: "سناریوی رشد فروش بهتر، هزینه کنترل‌شده و تامین مالی نرم‌تر.",
      adjustments: defaultScenarioAdjustments("optimistic"),
      assumptions: calculateScenarioAdjustedAssumptions(baseAssumptions, defaultScenarioAdjustments("optimistic")),
    },
    {
      id: "scenario-pessimistic",
      projectId: "solar-kerman",
      scenarioId: "scenario-pessimistic",
      version: 1,
      createdAt: now,
      updatedAt: now,
      name: "بدبینانه",
      type: "pessimistic",
      code: "S03",
      priority: 3,
      isActive: false,
      isLocked: false,
      isDefault: true,
      status: "active",
      description: "سناریوی فشار هم‌زمان بر فروش، هزینه و نقدینگی.",
      adjustments: defaultScenarioAdjustments("pessimistic"),
      assumptions: calculateScenarioAdjustedAssumptions(baseAssumptions, defaultScenarioAdjustments("pessimistic")),
    },
    {
      id: "scenario-fx-shock",
      projectId: "solar-kerman",
      scenarioId: "scenario-fx-shock",
      version: 1,
      createdAt: now,
      updatedAt: now,
      name: "شوک ارزی",
      type: "fx-shock",
      code: "S04",
      priority: 4,
      isActive: false,
      isLocked: false,
      isDefault: true,
      status: "active",
      description: "سناریوی افزایش نرخ‌های رسمی، آزاد و حواله‌ای ارز.",
      adjustments: defaultScenarioAdjustments("fx-shock"),
      assumptions: calculateScenarioAdjustedAssumptions(baseAssumptions, defaultScenarioAdjustments("fx-shock")),
    },
    {
      id: "scenario-inflation-shock",
      projectId: "solar-kerman",
      scenarioId: "scenario-inflation-shock",
      version: 1,
      createdAt: now,
      updatedAt: now,
      name: "شوک تورمی",
      type: "inflation-shock",
      code: "S05",
      priority: 5,
      isActive: false,
      isLocked: false,
      isDefault: true,
      status: "active",
      description: "سناریوی رشد تورم، دستمزد، انرژی، مواد و CAPEX.",
      adjustments: defaultScenarioAdjustments("inflation-shock"),
      assumptions: calculateScenarioAdjustedAssumptions(baseAssumptions, defaultScenarioAdjustments("inflation-shock")),
    },
    {
      id: "scenario-delay",
      projectId: "solar-kerman",
      scenarioId: "scenario-delay",
      version: 1,
      createdAt: now,
      updatedAt: now,
      name: "تاخیر اجرا",
      type: "delay",
      code: "S06",
      priority: 6,
      isActive: false,
      isLocked: false,
      isDefault: true,
      status: "active",
      description: "سناریوی افزایش مدت ساخت، تاخیر پرداخت CAPEX و فشار نقدینگی.",
      adjustments: defaultScenarioAdjustments("delay"),
      assumptions: calculateScenarioAdjustedAssumptions(baseAssumptions, defaultScenarioAdjustments("delay")),
    },
  ],
};
